### ISSUE TITLE
ios build

### ISSUE THREAD

**Issue by soundyogi** [ncsoft/Unreal.js#100]
As far as I understand there is no support fro ios so far.
Frida seems to use some kind of v8 build.

https://github.com/frida/v8

Could this help?

**Comment by nakosung** [comment]
Apple's policy prevents to use runtime machine code generation. Building v8 for iOS is a doable job but you cannot use v8 for JS engine. Apple accepts only JavascriptCore as embedded JS engine.

**Comment by soundyogi** [comment]
Thank you.
Bummer, but then ios will get left behind I guess :D

Thanks for this awesome project.
