### ISSUE TITLE
Compile Errors with 4.13 Preview 3

### ISSUE THREAD

**Issue by dsanjit** [ncsoft/Unreal.js#104]
I am trying to use this awesome plugin with UE4.13 Preview 3. I get these compile errors from the Unrealheader tool:

...Plugins/UnrealJS/Source/JavascriptWebSocket/JavascriptWebSocket.h(23): error : UFUNCTION inside this preprocessor block will be skipped
...Plugins/UnrealJS/Source/JavascriptWebSocket/JavascriptWebSocketServer.h(20): error : UFUNCTION inside this preprocessor block will be skipped

Any Suggestions ?

Thanks.

**Comment by nakosung** [comment]
Okay, I will try to build unreal.js with 4.13 preview.

**Comment by nakosung** [comment]
Fixed by https://github.com/ncsoft/Unreal.js-core/commit/3a1f7e11b2cb429083e1c20df73f0df4c58c780f
