### ISSUE TITLE
TypeError: require(...) is not a function...

### ISSUE THREAD

**Issue by tenowg** [ncsoft/Unreal.js#107]
I downloaded Unreal.js from the unreal marketplace (even just updated it before using) and this is the error I am getting after trying to follow the quick start tutorial... this is from the copied and pasted example script helloWorld.js

```
Error: e:\Program Files (x86)\Epic   Games\4.13\Engine\Plugins\Marketplace\UnrealJS\Content\Scripts\devrequire.js:19: TypeError: require(...) is not a function
Error: TypeError: require(...) is not a function
Error:     at default_exec (e:\Program Files (x86)\Epic Games\4.13\Engine\Plugins\Marketplace\UnrealJS\Content\Scripts\devrequire.js:19:31)
Error:     at devrequire (e:\Program Files (x86)\Epic Games\4.13\Engine\Plugins\Marketplace\UnrealJS\Content\Scripts\devrequire.js:26:19)
Error:     at module.exports (e:\Unreal Projects\MageWorld - Copy\Content\Scripts\bootstrap.js:12:30)
Error:     at e:/Unreal Projects/MageWorld - Copy/Content/Scripts/test.js:34:25
Error:     at e:/Unreal Projects/MageWorld - Copy/Content/Scripts/test.js:36:3
```

Everthing I did....

1) Downloaded from marketplace
2) Installed plugin to Engine
3) added plugin to project
4) updated plugin
5) tried to follow getting started video.

Thanks

**Comment by kelfire** [comment]
You are missing bootstrap.js file.  You can copy it from the example project into your own project.  Here is a link to a tutorial video (not mine) https://youtu.be/XxPSLjBg7DU?t=272

**Comment by tenowg** [comment]
Bootstrap.js has already been copied to script directory

**Comment by kelfire** [comment]
Paste your code from test.js on here.  I had the same issue before.

**Comment by tenowg** [comment]
```
/// <reference path="typings/ue.d.ts">/>
// ; typing info for auto-completion in Visual Studio Code

"use strict"

function main() {
    // create a new actor
    // ; new ActorClass(world{World}, location{Vector}, rotation{Rotator})
    let actor = new TextRenderActor(GWorld,{X:100,Z:100},{Yaw:180})

    // initialie its text render component
    actor.TextRender.SetHorizontalAlignment('EHTA_Center')
    actor.TextRender.SetText('Hello World')

    // clean up the mess
    return function () {
        actor.DestroyActor()
    }
}

// bootstrap to initiate live-reloading dev env.
try {
    module.exports = () => {
        let cleanup = null

        // wait for map to be loaded.
        process.nextTick(() => cleanup = main());

        // live-reloadable function should return its cleanup function
        return () => cleanup()
    }
}
catch (e) {
    require('bootstrap')('helloWorld')
}
```

**Comment by tenowg** [comment]
I think I might see an issue...

**Comment by kelfire** [comment]
**change** 
catch (e) {
    require('bootstrap')('helloWorld')
}

**to**
catch (e) {
    require('bootstrap')('test')
}

**Comment by tenowg** [comment]
haha, yea, saw that right before you posted... it removes the error, thanks

**Comment by kelfire** [comment]
Just a warning.  If you are using the Unreal.js from the market version 0.2.  It can crash after 5-10 minutes i.e.(run the hellocharacter.js).  Luckily, there is a new version on the github 0.2.1 that fixes it.

**Comment by nakosung** [comment]
I have updated troubleshooting guide in wiki. :) https://github.com/ncsoft/Unreal.js/wiki/Troubleshooting

**Comment by tenowg** [comment]
current version on Marketplace is "VersionName" : "0.2.1", at least according to the uplugin file. I believe that was the update I got before I started this.

**Comment by mflux** [comment]
I still get this in a packaged build.

In a cooked project CPCS/Content/Scripts/cpcsruntime.js

    try {
      module.exports = () => {
        let cleanup = null;
        process.nextTick(() => cleanup = main());
        return () => cleanup();
      };
    }
    catch (e) {
      require('bootstrap')('cpcsruntime');
    }


Error log:

    [2017.09.12-21.40.49:532][  0]Javascript:Error: file:///c:/CPCS/WindowsNoEditor/CPCS/Content/Scripts/bootstrap.js:12: TypeError: require(...) is not a function
    [2017.09.12-21.40.49:532][  0]Javascript:Error: TypeError: require(...) is not a function
    [2017.09.12-21.40.49:532][  0]Javascript:Error:     at module.exports (file:///c:/CPCS/WindowsNoEditor/CPCS/Content/Scripts/bootstrap.js:12:30)
    [2017.09.12-21.40.49:532][  0]Javascript:Error:     at file:///c:/CPCS/WindowsNoEditor/CPCS/Content/Scripts/cpcsruntime.js:287:25
    [2017.09.12-21.40.49:532][  0]Javascript:Error:     at file:///c:/CPCS/WindowsNoEditor/CPCS/Content/Scripts/cpcsruntime.js:289:3
    [2017.09.12-21.40.49:532][  0]Javascript:Error:     at file:///c:/CPCS/WindowsNoEditor/CPCS/Content/Scripts/cpcsruntime.js:298:3

**Comment by nakosung** [comment]
ping @crocuis

**Comment by crocuis** [comment]
Check if UnrealJS Plugin script exists. Copy of Non Asset file of Plugin is not supported, so you have to copy it manually.

**Comment by mflux** [comment]
That did it, thank you. The wiki documentation for cooking / packaging should probably be updated with:

- need to manually copy Plugins/UnrealJS/Content folder into the output package

I wish there was a way to automate this. I looked into using https://answers.unrealengine.com/questions/411431/prepost-build-step-in-ubt.html post build step but couldn't get the game's target folder. Maybe you guys can write a plugin module change like https://answers.unrealengine.com/questions/402515/how-to-modify-build-file-to-copy-dlls-to-binaries.html to have it automatically copy over? Seems really important.

**Comment by mflux** [comment]
Ahhh

> Current version of UnrealEngine doesn't handle plugins with Content correctly. For a workaround you may copy Plugins/UnrealJS/Content into cooked target manually.

So that's what that means.

**Comment by imre-chroncsik** [comment]
With the 4.19 update, in Unreal.js-demo's app.js, the following line: 
`	require('bootstrap')('app')`
has been replaced with this: 
`	require('bootstrap')(__filename)`
	
For me, this change causes "TypeError: require(...) is not a function". 

Reverting back to 'app' instead of __filename fixes it. I'm not sure why.
