### ISSUE TITLE
Adding to Arrays

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#11]
It wasn't clear from the documentation, as well as reading the source.

Creating a new property array looks like:

        properties() {
            this.vertices/*Vector[]*/;    
            this.triangles/*int[]*/;
        }    

However doing none of the following worked:

            this.vertices.add({X:0,Y:0,Z:0});
            this.vertices.Add({X:0,Y:0,Z:0});

            this.vertices = [];
            this.vertices.push({X:0,Y:0,Z:0});

A few questions 

* What's the proper way to instantiate an array? How do you modify the array?
* Do properties overwrite inherited properties? For example if this class's baseclass already has a vertices array made from a blueprint, does this reference the underlying class' vertices array? Or is it creating a new one?

**Comment by mflux** [comment]
Also
            this.vertices.push({X:0,Y:0,Z:0});
            console.log( 'vertices in beginplay', this.vertices.length );

Will reveal

    < vertices in beginplay 0

**Comment by mflux** [comment]
Assuming arrays are TArrays https://docs.unrealengine.com/latest/INT/Programming/UnrealArchitecture/TArrays/index.html

These will not work either:

            this.vertices.Init( 10, 5 );
            this.vertices.Append( {X:0,Y:0,Z:0} );

**Comment by nakosung** [comment]
Please see https://github.com/ncsoft/Unreal.js/wiki/Dynamic-array:-Limitation. Currently dynamic array isn't fully implemented.

To answer to your question, properties are inherited from their base class.

**Comment by mflux** [comment]
Ah thanks! I assume that means the dynamic arrays are also inherited, it's just not working at the moment?

**Comment by mflux** [comment]
Oh I got it.

this.vertices = [ { X: 0, Y: 50, Z: 50 },  { X: 200, Y: 0, Z: 0 }, { X: 200, Y: 200, Z: 0 } ]; 

This works.

**Comment by nakosung** [comment]
Okay, then I'll close this issue. :+1:
