### ISSUE TITLE
JavascriptWebSocketServer is not defined

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#113]
Strangely, it seems the JavascriptWebSocket module is not exposed anymore.

**Comment by arthursw** [comment]
Note: my goal is to communicate between Unreal.js and an SWebBrowser, but as I explained in [this question](https://answers.unrealengine.com/questions/495638/how-to-bind-uobject-to-webbrowser.html), I didn't manage to send parameters from browser to UE, neither to return values.

**Comment by nakosung** [comment]
If you couldn't pass arguments and read return value, using your UObject as a 'scratch board' might hack the problem.

`class UYourUObject {
  UPROPERTY()
  int ArgA;
  UPROPERTY()
  int ReturnValue;
  UFUNCTION()
  void TheFunction(); // No input args, no return value.
}`

void UYourUObject::TheFunction() {
  auto InputArg = this->ArgA;
  auto& ReturnValue = this->ReturnValue;

  // your logic goes here.
}

**Comment by arthursw** [comment]
I can't even access the properties of my UObject. 
It's purely defined in javascript as followed:

```javascript
class JSLink extends JavascriptObject {
    
    constructor() {
        super()
    }

    ctor() {
        this.Name = 'JSLink';
    }

    properties() {
        this.Name /* String */;
    }

    DownloadPlugin(PluginName) /* BlueprintCallable */ {
        console.log("DownloadPlugin: " + PluginName);                          // PluginName is always null
        global.ProBuilder.PluginManager.DownloadPlugin(PluginName);
    }
}
```

**Comment by nakosung** [comment]
So you cannot access UObject's from delegate function which is bound via BindUObject? It seems it has lost track of UObject somehow. Dirty hack could be done by using global scratch pad(global js variables).

**Comment by arthursw** [comment]
I don't really understand, how would you do that?

**Comment by nakosung** [comment]
Oh, I misunderstood your problem. You are trying to read args which are passed via delegate. What if you use normal BP delegates instead of BindUObject delegate? Pass your native function to BindUObject and your native function just fires BP delegate.

```cpp
UPROPERTY(BlueprintAssignable)
FDelegateSignature OnDelegate;

UFUNCTION()
void YourNativeFunction(int arg)
{
  OnDelegate.Broadcast(arg);
}
```

**Comment by arthursw** [comment]
I still don't get it. But this issue is more about JavascriptWebSocketServer. [This question](https://answers.unrealengine.com/questions/495638/how-to-bind-uobject-to-webbrowser.html) is more appropriate to discuss about the UObject binding.

**Comment by nakosung** [comment]
JavascriptWebSocket is back.
