### ISSUE TITLE
Getting local ip address of running websocket server

### ISSUE THREAD

**Issue by pwnpwn** [ncsoft/Unreal.js#116]
Hi!
Is it possible to get the local ip address of the machine Unreal JS is running on? Either with JavascriptWebsocketServer or other means. I have really tried to figure out if this is possible, but have come up empty with good solutions. All the node modules I have found for this requires window or something similar and I don't want to convert to c++ either if possible.

**Comment by nakosung** [comment]
Current web socket server implementation of UnrealEngine listens on all available network interfaces. 

I suggest that you could retrieve the list by exposing `ISocketSubSystem::GetLocalAdapterAddresses, GetLocalBindAddr, GetLocalHostAddr' to BP within your own `UBlueprintFunctionLibrary`.

**Comment by pwnpwn** [comment]
Ok I see. I guess this issue is not very related to Unreal.js then if I go down the C++ route of solving it.
But thank you for the help anyways!

**Comment by nakosung** [comment]
@pwnpwn 👍 Closing this issue.
