### ISSUE TITLE
Is it possible to run a script without having a file

### ISSUE THREAD

**Issue by drfrev** [ncsoft/Unreal.js#117]
I know it's possible to set the js file in c++ using
`JSEngine->ScriptSourceFile = "file.js";`

But is it possible to set the code without having a file, such as
`JSEngine->ScriptSource = "if (2+2==4) {console.log('hello');}";`

I am looking for a method to write and run the javascript code while the game is running from an in-game console.

**Comment by nakosung** [comment]
You can run string with RunScript method.

**Comment by drfrev** [comment]
Can't believe I didn't find that, my bad.
