### ISSUE TITLE
Invoking JS function from c++ with parameters

### ISSUE THREAD

**Issue by sascha1337** [ncsoft/Unreal.js#119]
Hey, since 2 day's im trying to run a js function emitted by an existing c++ actor.

I tried to create a c++ Actor with BlueprintImplementableEvent, i can use it in Blueprint.

Now, tried to create a subclass from that c++ Actor class and overwrite the function, no success.
Then i created a Blueprint that inherit from my c++ Actor, same not working yet.

I can see my function being called inside the blueprint, so i thought i could create a blueprint function and overwrite that to get the data inside unreal.js - no success either.

Should i use multicast delegate ? Can i implement these events in js ?

I'd love to see some workflow that allows to call a function in c++ and is being received in js via "me.on("cpp_event",() => ..."

Heres some JS code..

```
         class UdpClient extends Blueprint.Load('/Game/UDP_B').GeneratedClass {
             constructor(){
                super();
            }
        ctor() {
            // Subobject initialization, property initialization
            this.bAlwaysRelevant = true
        }
          // THIS IS NOT WORKING
        MyFunc()
            console.log("INSIDE JS");
        }
          // FUNCTION THAT WORKS INSIDE BLUEPRINT, UNFORTUNATLY NOT FIRED HERE 
        MCEvent(actor) {
            console.log("****");
            return blax(actor);
            // return call_your_js_func(actor)
        }
        blax(a){
            console.log("**Y*Y*Y*Y*Y*Y*Y*");
         }
         }

        let MyActor_Cx = require('uclass')()(global,UdpClient)
        var blax = new MyActor_Cx(GWorld,{X:1});
```

**Comment by nakosung** [comment]
Actually it is possible to make js functions called as blueprint implementable events. (there are many real usages (https://github.com/ncsoft/Unreal.js-core/search?utf8=%E2%9C%93&q=implementable&type=Code)

JS event handler
https://github.com/ncsoft/Unreal.js/blob/3f3cd4bfa65769089855b403289c9893aa27b4e9/Examples/Content/Scripts/helloUMG.js#L59

Call from C++
https://github.com/ncsoft/Unreal.js-core/blob/a9f5ee96122b149e4e0663d24459124b4c9b3b4b/Source/V8/Private/JavascriptOutputDevice.cpp#L38
