### ISSUE TITLE
2048 Example errors

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#12]
Console logs:

    LogLinker: Warning: The file '../../../../../../Users/Flux/Documents/Unreal Projects/unrealjs 4.10/Content/Color.uasset' contains unrecognizable data, check that it is of the expected type.
    LogLinker: Warning: The file '../../../../../../Users/Flux/Documents/Unreal Projects/unrealjs 4.10/Content/Color.uasset' contains unrecognizable data, check that it is of the expected type.
    LogUObjectGlobals: Warning: Failed to find object 'Material /Game/Color.Color'
    Error: TypeError: Cannot read property 'SetVectorParameterValue' of undefined
    Error:     at Object.tile.set_color (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:199:29)
    Error:     at Object.tile.set_value (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:128:26)
    Error:     at Actuator.addTile (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:269:21)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:233:34
    Error:     at Array.forEach (native)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:231:28
    Error:     at Array.forEach (native)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:230:28
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\animframe_polyfill.js:10:17
    Error:     at invoke_next (C:/Program Files (x86)/Epic Games/4.10/Engine/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
    Error: TypeError: Cannot read property 'SetVectorParameterValue' of undefined
    Error:     at Object.tile.set_color (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:199:29)
    Error:     at Object.tile.set_value (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:128:26)
    Error:     at Actuator.addTile (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:269:21)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:233:34
    Error:     at Array.forEach (native)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:231:28
    Error:     at Array.forEach (native)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:230:28
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\animframe_polyfill.js:10:17
    Error:     at invoke_next (C:/Program Files (x86)/Epic Games/4.10/Engine/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
    Error: TypeError: Cannot read property 'SetVectorParameterValue' of undefined
    Error:     at Object.tile.set_color (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:199:29)
    Error:     at Object.tile.set_value (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:128:26)
    Error:     at Actuator.addTile (C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:269:21)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:233:34
    Error:     at Array.forEach (native)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:231:28
    Error:     at Array.forEach (native)
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\actuator.js:230:28
    Error:     at C:\Users\Flux\Documents\Unreal Projects\unrealjs 4.10\Content\Scripts\2048\game\animframe_polyfill.js:10:17
    Error:     at invoke_next (C:/Program Files (x86)/Epic Games/4.10/Engine/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)

![2048screen](https://cloud.githubusercontent.com/assets/1041360/11415977/5c4e185e-93be-11e5-8689-5c803a09a37e.png)

**Comment by nakosung** [comment]
I think you had not installed `git-lfs` correctly. Not having `git-lfs`, your `*.uasset`, `*.umap` are not safe to read by engine.

**Comment by mflux** [comment]
Aha, I'll give that a check thanks.

**Comment by nakosung** [comment]
@mflux bump
