### ISSUE TITLE
Plugin 'UnrealJS' failed to load...

### ISSUE THREAD

**Issue by matthewsimo** [ncsoft/Unreal.js#121]
Hello - I just installed this plugin from the marketplace on a mac and get this error when trying to  launch UE 4.13.1 - http://mas.im/hslf

I saw the other issue that was similar to this issue but that was on windows so I thought it best to open a new issue instead. Has anyone seen this before? Am I missing something basic here?

Thanks!

**Comment by nakosung** [comment]
I just found that osx build has some issues with *.dylib. Workaround is like below: 

1. Locate your UnrealJS folder.
2. Copy {UnrealJS}/ThirdParty/v8/lib/Mac/x64/*.dylib to /usr/local/lib

**Comment by matthewsimo** [comment]
This worked like a charm, thank you! :D
