### ISSUE TITLE
Missing libs for linux

### ISSUE THREAD

**Issue by Deams51** [ncsoft/Unreal.js#127]
Hi,
Let me start by saying thanks and good job! :) 

Alright, was looking for the libs for Linux, but it seems you dropped support for it a while ago.
Is there any specific reasons?
In the meantime, I will try to cross-compile V8 using UE toolchain. If you have a proper compile flow already set up, would you be willing to share it?

**Comment by nakosung** [comment]
@Deams51 Just because I don't have enough time to support multiple platforms.

**Comment by Deams51** [comment]
Missed your updates! :) 
Nice to see that you got it to compile. Got it here but with a different build process, will check yours out when I can catch a break.
