### ISSUE TITLE
Environment map in custom JavascriptEditorViewport

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#128]
I use a `JavascriptEditorViewport` for the UV Editor of ProBuilder. 

Now that I updated Unreal.js / UE, there is a sphere with an environment map on it in the custom `JavascriptEditorViewport`. Since I need an orthographic view to manipulate UVs, I would like to remove the sphere.

How can I do that?

**Comment by nakosung** [comment]
It must be a sky component. I think you can remove the component by calling `viewport.GetSkyComponent().DestroyComponent()`.

**Comment by arthursw** [comment]
Great! Thanks! I also had to call `viewport.GetFloorMeshComponent().DestroyComponent()` and now it's perfect 👍 !
