### ISSUE TITLE
Question : why was JavascriptWebSocket removed ? Has it been replaced ?

### ISSUE THREAD

**Issue by VRTracker** [ncsoft/Unreal.js#129]
Hi !
This is not an issue, I just was trying to use JavascriptWebSocket from your examples and trying to figure out why it wouldn't work. 
I finally found out that it was removed last month.
May I know why it has been removed ? Is it replaced by something else, or there is no way to use Websockets anymore ? I was implementing Unreal JS just because of Websocket support.

Regards,
Jules

**Comment by nakosung** [comment]
In 4.14, libwebsocket has been updated with newer version which has slightly changed its api. I thought libwebsocket didn't have to be included within unreal.js, but recently I added v8 chrome debugger support for 4.14 which implemented with libwebsocket. So I think it would be possible to resurrect JavascriptWebSocket library. :)

**Comment by VRTracker** [comment]
Thank you for taking the time to answer and explain ! Are you calling the
libwebsocket included in Unreal experimental plugins or this is the usual
javascript version ?
If you happened to resurrect it one day, please drop me a quick note ;)

BTW : awesome work on the overall plugin ! This is very impressive  !

Le 10 déc. 2016 02:59, "Nako Sung" <notifications@github.com> a écrit :

In 4.14, libwebsocket has been updated with newer version which has
slightly changed its api. I thought libwebsocket didn't have to be included
within unreal.js, but recently I added v8 chrome debugger support for 4.14
which implemented with libwebsocket. So I think it would be possible to
resurrect JavascriptWebSocket library. :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ncsoft/Unreal.js/issues/129#issuecomment-266188684>,
or mute
the thread

**Comment by nakosung** [comment]
@VRTracker I just updated in another branch. (https://github.com/ncsoft/Unreal.js-core/tree/v8inspector_57) This branch requires v8 5.7, which has been uploaded in https://github.com/ncsoft/Unreal.js-core/releases/tag/v8-5.7.137.

**Comment by nakosung** [comment]
@VRTracker And it is now on master.
