### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by nakosung** [ncsoft/Unreal.js#130]

**Comment by nakosung** [comment]
![image](https://cloud.githubusercontent.com/assets/2463571/21081740/21f871ca-c010-11e6-8c7d-486fdef4c7b7.png)

**Comment by arthursw** [comment]
Wow! Did you manage to debug with the chrome dev tools? How? I'll retry tomorrow...

**Comment by arthursw** [comment]
I install devtool (`npm install devtool -g`), ran `Context.SetAsDebugContext()` in the Unreal.js console,  and went to this URL in chrome: `chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:5858` 
(I also tried port `9229`).

I got the following output in the Unreal.js console:

< V8 Debugger session start
Error: invalid content length < 0
< V8 Debugger session stop

What should I do?

**Comment by nakosung** [comment]
@arthursw Context.SetAsDebugContext() initiates v8 debugger protocol, not a chrome devtools protocol. You can use `Context.CreateInspector()` to open chrom devtools port. :)

**Comment by arthursw** [comment]
Ok I didn't see this wiki page: https://github.com/ncsoft/Unreal.js/wiki/V8-inspector

Great !!!

**Comment by mgtc** [comment]
Hi,

Why I use Context.CreateInspector(9229) before my code, It show error: "TypeError: Context.CreateInspector is not a function" in Javascript console windows.

my project unreal.js version is 0.2.3, and install unreal.js from unreal marketplace.

can you tell me  how to use the Context.CreateInspector more detail?

**Comment by nakosung** [comment]
@mgtc It isn't up-to-date, Current version is 0.2.5. Please update your installed plugin via launcher.
