### ISSUE TITLE
BP Functions become undefined when BP function binds to event

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#131]
Fairly simple BP. Note the event bind is not run yet.

![screenshot 2016-12-13 04 13 40](https://cloud.githubusercontent.com/assets/1041360/21140000/982997f4-c0ea-11e6-94fa-1511623dac5c.png)

However, when attached:

![screenshot 2016-12-13 04 14 43](https://cloud.githubusercontent.com/assets/1041360/21140023/b852a3cc-c0ea-11e6-9c18-4be2ab652dcd.png)

    Javascript:Error: c:\Users\Flux\Documents\Unreal Projects\CPCS\Content\Scripts\game\gameview.js:1722: TypeError: corporationsHUD.addToCorporationList is not a function
    Javascript:Error: TypeError: corporationsHUD.addToCorporationList is not a function

I'm not sure if this is because I'm running a (~4month) old build.

**Comment by nakosung** [comment]
@mflux Can you provide simple repro steps? By the way we have open sourced react-umg for UI's. :)

**Comment by mflux** [comment]
I'll upgrade to the latest and find out if this is still happening.

**Comment by mflux** [comment]
This issue seems to have been fixed, I couldn't reproduce it anymore.
