### ISSUE TITLE
Crash while calling non static function as static function.

### ISSUE THREAD

**Issue by nakosung** [ncsoft/Unreal.js#140]
It should not crash. :) (reported by https://github.com/ncsoft/Unreal.js/issues/139)

**Comment by nakosung** [comment]
It never happen. Closing this issue.

**Comment by FredyC** [comment]
I am confused. In the other issue you said it's happening in unreal engine :) Are you going to report it there then? I am not really sure what I would call it.

**Comment by nakosung** [comment]
It only crashes only when code tries to execute UWorld::SomeMethod with invalid UWorld instance. So it is not a bug of unreal.js. UnrealEngine seems to have many methods having this symptom so I'm not going to report this issue to epic.

For javascript programmers' sake, I think it is possible to catch native/C++ exception and throw an exception to v8, but I don't think this is not a right way to handle native crash.

**Comment by FredyC** [comment]
@nakosung  And what would be right way according to you? In my opinion it's the Unreal.JS plugin which sits at the first front before actually running the code in UE. Why it cannot be handled in a plugin itself and catch exceptions in executed JS code before they have a chance to propagate to UE?

**Comment by nakosung** [comment]
@FredyC Native exception like SEGFAULT cannot be handled gracefully. It is not a designed catchable-exception.

**Comment by FredyC** [comment]
> I think it is possible to catch native/C++ exception and throw an exception to v8 but I don't think this is not a right way to handle native crash.

Seems to be that it's actually only way or do you have any other suggestion? Hard to be believe that only other way is to let it crash. I haven't even started to use Unreal.JS for real yet as it's rather annoying to have UE crashing all the time just because I am not familiar with API and call something that's not right :(
