### ISSUE TITLE
Set min/max values with Property Editor?

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#142]
Where can I find documentation about the property editor?

I would like to set a min / max for a slider created with UPropretyEditor, like in the [Spiral Generator](https://github.com/ncsoft/Unreal.js/blob/3f3cd4bfa65769089855b403289c9893aa27b4e9/Examples/Content/Scripts/extension-spiralGenerator.js#L210) example.

From UE "PropertyHandleImpl.cpp" (line 983) I understood that we must set `ClampMin` and `ClampMax` in the property meta data. But it seems impossible to set meta data from Unreal.js.

I could create a C++ function to set the metadata of any given property but I wonder if it's the best way.

The solution I can use for now is to react to the `OnChange` event, and clamp the value their, maybe resetting the slider to clamped value manually...

(The UE PropertyEditor Module is complicated and hard to read)

**Comment by nakosung** [comment]
You can set meta data of properties by declaring your properties like below:
```
properties() {
  this.X; /*float+EditAnywhere+ClampMin:0.1+ClampMax:0.4*/
}
```

https://github.com/ncsoft/Unreal.js-demo/blob/master/Content/Scripts/json2u.js#L52

**Comment by arthursw** [comment]
Is there a way to control the PropertyEditor children? 

I would like to show/hide some properties in the GUI.

My PropertyEditor elem has no children:

```
let MyPropertyEditorElem = null

UMG(PropertyEditor, {},
            $link: elem => {
                  MyPropertyEditorElem = elem;          // elem.children is always empty !!!
            },
            $unlink: elem => {[...]}
})
```

**Comment by arthursw** [comment]
Actually this is a different issue (it's more a question), I'll open a new one.

**Comment by arthursw** [comment]
And thank you for providing me the link to json2u, I'll change it for my use 👍
