### ISSUE TITLE
How to access objects placed with editor?

### ISSUE THREAD

**Issue by jeffersondarcy** [ncsoft/Unreal.js#145]
I am a beginner with unreal(-.js). If I place any objects with editor, I can access them in C++ with GetOwner and I have inherited methods BeginPlay() and TickComponent(). What would be the Unreal.js way to interact with this objects? Do you allways create blueprints and override the methods with js or how is it done?

**Comment by nakosung** [comment]
Programming pattern should be altered a little bit. Main tick loop should be implemented in javascript. Then you can create/manipulate/destroy actors within that function. You may check https://github.com/ncsoft/Unreal.js-demo to see how this pattern can be implemented.

**Comment by jeffersondarcy** [comment]
thx
