### ISSUE TITLE
Using unreal.js with node-serialport

### ISSUE THREAD

**Issue by xseignard** [ncsoft/Unreal.js#147]
Hello,

First of all, thanks for your nice work. I'm more a node.js guy than a UE one. I want to create a VR experiment with the HTC Vive + some actuators for a dynamic seat.

Since I'm very used to node-serialport (https://github.com/EmergingTechnologyAdvisors/node-serialport) to handle serial communications, I'd like to use it alongside to unreal.js.

And since node-serialport is a native c++ node.js library, will it work? And will it be packable?

Regards

**Comment by nakosung** [comment]
Unfortunately native node.js modules are not compatible with unreal.js. Instead you can relay your requests to node.js server via websocket.

**Comment by xseignard** [comment]
Thanks for your quick answer!

That's what I was fearing. Websockets then!

Regards
