### ISSUE TITLE
Severe lag when adding javascript via C++

### ISSUE THREAD

**Issue by drfrev** [ncsoft/Unreal.js#149]
The following line of code is being called during the constructor of an actor:

`UJavascriptComponent* JSEngine = CreateDefaultSubobject<UJavascriptComponent>(TEXT("Javascript"));`

When the actor is spawned into the scene I get a 1/4 second hang. I found that adding the javascript component is causing this lag, having the javascript code run does not cause any problems. Am I doing this incorrectly?

**Comment by nakosung** [comment]
You should keep number of javascript contexts minimal. Ordinary actors are not good places to attach javascript component. Instead you may attach it to some *singleton* actor.

**Comment by drfrev** [comment]
I have a need for there to be multiple individual codes running simultaneously without a shared environment. Is this possible?
