### ISSUE TITLE
Having trouble with installation instructions..

### ISSUE THREAD

**Issue by andyfischer** [ncsoft/Unreal.js#15]
Hi, the setup instructions are giving me some issues..

> Install git-lfs first to download *.umap, *.uasset properly. (https://git-lfs.github.com/)

I would suggest saying that you need to run `git lfs fetch`, this is hard to figure out if someone hasn't used `git lfs` before.

> Download prebuilt UnrealJS plugin and unzip into Playground/Plugins/UnrealJS.

Where do you find this download, and where is the Playground/ directory? (I'm guessing that the Unreal.js repo should be cloned with the name Playground?)

> cd .../Content/Scripts && npm i to install node.js packages.

Is this supposed to be inside /Plugins/UnrealJS/Content/Scripts or inside /Examples/Content/Scripts ?

The command `npm i` doesn't work when inside /Plugins/UnrealJS/Content/Scripts because there is no `package.json` file there. But it looks like `node_modules` is already there so `npm i` is not necessary.

> Activate JavascriptConsole by clicking Windows - Developer Tools - JavascriptConsole.

When I try, the JavascriptConsole does not show up in that menu. I'm guessing that I missed one of the setup steps..

Anyway thanks for making this cool project open source!

**Comment by nakosung** [comment]
I also think that documentation needs to be more precise and friendly. 

`node_modules` of the plugin are preinstalled, so there is no need to `npm i` in `/Plugin/UnrealJS/Content/Scripts`. 

You should unzip plugin into `ExampleGame` directory, so the final directory layout should be like;

```
ExampleGame/
                         Content/
                                      Scripts/
                         Plugins/
                                      UnrealJS/
                                                      Content/
```

**Comment by andyfischer** [comment]
Thanks for improving the docs.

Still a little confused by:

> Download prebuilt UnrealJS plugin and unzip into Examples/Plugins/UnrealJS.

Where do I find the prebuilt UnrealJS plugin?

**Comment by nakosung** [comment]
You can find prebuilt zip file under `releases tab`.
