### ISSUE TITLE
why v8?

### ISSUE THREAD

**Issue by gastrodia** [ncsoft/Unreal.js#153]
why v8? not directly embed nodejs, so we can use all node modules

**Comment by stt** [comment]
...node.js is a framework for webapps that runs on top of v8

look into [examples](https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/package.json), it uses npm

**Comment by nakosung** [comment]
As @stt mentioned, you can use plenty of npm modules with unreal.js already.
