### ISSUE TITLE
Inheriting JS class as a Blueprint?

### ISSUE THREAD

**Issue by FredyC** [ncsoft/Unreal.js#155]
I might be missing something. I tried adding the JavascriptComponent to the GameMode so it's always running the script, but for some reason when I want to create a BP out of the JS class I've defined, I cannot seem to find it in the list. Is it possible to do that? Obvious use case is to write the harder part of logic in a code and then customize the actor further with blueprint easiness.

**Comment by nakosung** [comment]
Extending JS with BP isn't supported. Splitting logic into two parts (js and bp) might be the way.

**Comment by FredyC** [comment]
As much as I would love to use JS for my game I find this kinda cumbersome compared to C++ coding. I suppose you don't even plan to extend it this way.

**Comment by Youdaman** [comment]
The other way to do it would be do your stuff in BP then extra parts in JS -- you can load/use BPs in JS, just not JS in BP (as far as I understand). You can call JS from C++ and vice versa though.

**Comment by FredyC** [comment]
@Youdaman can you please show me how to call JS from C++? That would be very helpful indeed. I have seen comment in #150 about using `CallJS`, but as I am total newbie to C++ world and I am unsure how would I do that.

**Comment by Youdaman** [comment]
@fredyc I was thinking of #150 also. I can't find anything in the repo so I'm guessing @nakosung might mean https://github.com/bfulgham/CallJS/blob/master/README.md

There's also http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code

**Comment by FredyC** [comment]
Well I did found this in Unreal.JS code, but I am unsure how to actually use it.

https://github.com/ncsoft/Unreal.js-core/blob/master/Source/V8/Public/JavascriptLibrary.h#L507-L526

**Comment by Youdaman** [comment]
My guess would be you call it as `CallJS(someFunction, params);` in C++ when you would say `someFunction(params)` in JS? The params are a struct (like an object in JS).

**Comment by FredyC** [comment]
Well, but how to define that `someFunction`? Like a string of JS code?

**Comment by Youdaman** [comment]
I assume it's a function you've already defined in your Unreal.js scripts, and CallJS just lets you call it from C++

**Comment by FredyC** [comment]
I guess this can be closed, I've given up on understanding this. Seems much easier to just learn C++ than how to bend over this thing.
