### ISSUE TITLE
TypeScript errors

### ISSUE THREAD

**Issue by Cnnamon** [ncsoft/Unreal.js#164]
Hi,

i launched a project with typescript and got the following errors:

![image](https://cloud.githubusercontent.com/assets/7039823/24325351/c5a458ee-119f-11e7-9a1d-beec5dbe1efb.png)

**Comment by ConquestArrow** [comment]
Hi, I also wrote scripts for Unreal.js with TypeScript (ver. 2.2.x).
Please try before settings in a your `tsconfig.json`.

```json
{
    "compilerOptions": {
        "lib": [
            "es2016"
        ],
        "skipDefaultLibCheck": true,
        "skipLibCheck": true,
        //etc...
    }
}
```

 - Duplicate identifier errors:
   - API names of some of the DOM API and Unreal is the same.
   - Unreal.js and UnrealEngine API has **not** DOM/BOM API.
   - Please specify pure ECMAScript (eg `es2016`) with` lib` compiler option.
   - _Exceptions:_ Some APIs implemented by V8 such as `console.log` should be copied from` lib.d.ts` to `console.d.ts` etc., please make it.
 - Incorrectly extends errors:
    - [TypeScript can not grammatically override static methods with incompatible argument types. ](http://www.typescriptlang.org/play/#src=declare%20class%20Parent%7B%20%7D%0Adeclare%20class%20Child%20extends%20Parent%7B%20%7D%0A%0Adeclare%20class%20A%7B%0A%20%20%20%20static%20overridable(param%3A%20Parent)%3A%20void%3B%0A%20%20%20%20static%20noOverride(param%3A%20number)%3A%20void%3B%0A%7D%0A%0Adeclare%20class%20ChildNoError%20extends%20A%7B%0A%20%20%20%20static%20overridable(param%3A%20Child)%3Avoid%3B%0A%7D%0A%0Adeclare%20class%20ChildError%20extends%20A%7B%0A%20%20%20%20%2F%2F%60string%60%20is%20not%20child%20of%20%60number%60%0A%20%20%20%20static%20noOverride(param%3A%20string)%3A%20void%3B%0A%7D)
    - Unreal's C++ API is not.
    - Set skip lib checks. ;)

**Comment by Cnnamon** [comment]
Thanks that helped me 👍
