### ISSUE TITLE
Struct keys should use "friendly" name in JS

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#166]
# Issue
UE4 structs, when resolved in JS, have keys as

`mesh_9_A0152A134F4AD9E81F222DB2C09503DD`

instead of 

`mesh`

Unreal.js should convert the key name to friendly name.

# Use case

I'm trying to use UE4's structs to store meta data about models. For example, a mesh /Game/Geometry/rooftop/roof_container.roof_container has width 0.5, height 0.5

![screenshot 2017-04-08 14 46 13](https://cloud.githubusercontent.com/assets/1041360/24832699/2fa2443e-1c6a-11e7-8d11-0aef06ea15d7.png)

and I have a data-table full of these:

![screenshot 2017-04-08 14 46 58](https://cloud.githubusercontent.com/assets/1041360/24832705/47a23cc4-1c6a-11e7-874b-127b1530d40f.png)

I'm trying to use BP to pass it to JS so that I can get an array of these models for the procedural generator to mess with:

![screenshot 2017-04-08 14 48 07](https://cloud.githubusercontent.com/assets/1041360/24832710/796f872a-1c6a-11e7-80f6-99e681d8d2de.png)

Unfortunately, the JSON.stringified console log result shows the keys all have some strange ID attached to them:

      [
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_container.roof_container",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        },
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_control_room.roof_control_room",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        },
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_cooling.roof_cooling",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        },
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_short_silo.roof_short_silo",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        },
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_small_silo.roof_small_silo",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        },
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_solar_array.roof_solar_array",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        },
        {
          "mesh_9_A0152A134F4AD9E81F222DB2C09503DD": "/Game/Geometry/rooftop/roof_sphere_silo.roof_sphere_silo",
          "width_13_7E1B76F9485AADC1B6B73B971FECE79C": 0.5,
          "height_14_E4E60FDA45BEFAE8E6F4EE82461D16AB": 0.5
        }
      ]

I could strip them out with string manipulation, however this seems like a bug? Or am I doing it wrong?

**Comment by nakosung** [comment]
UE Script Struct has weird key names, but friendly name is being displayed on BP editor. 
https://github.com/EpicGames/UnrealEngine/blob/76085d1106078d8988e4404391428252ba1eb9a7/Engine/Source/Runtime/Engine/Classes/Engine/UserDefinedStruct.h#L39 

Display names are determined by `PropertyNameToDisplayName`. https://github.com/EpicGames/UnrealEngine/blob/76085d1106078d8988e4404391428252ba1eb9a7/Engine/Source/Runtime/Engine/Private/UserDefinedStruct.cpp#L159

So stripping names seems quite normal. :)

**Comment by mflux** [comment]
Hm, ok! But when would a user ever need the "weird" key name? Seems to me the user of unreal.js would only ever want friendly name.

**Comment by nakosung** [comment]
Special code path(Read/Write property) for UserDefinedStruct could be made. Please post an issue for it!

**Comment by mflux** [comment]
I guess this is the issue ;) I will modify the OP.

**Comment by nakosung** [comment]
@mflux Oops! :)

**Comment by mflux** [comment]
This can get pretty bad when you consider the output of the struct actually has no properties of its own so..

`Object.keys( struct ) // returns []`

So in order to actually fix the keys one must do...

`JSON.parse( JSON.stringify( struct, null, 2 ) ) ; // correct output`

**Comment by nakosung** [comment]
Fixed by https://github.com/ncsoft/Unreal.js-core/commit/4fc66ced6692156bdc8f6b819571b807028b5618.
