### ISSUE TITLE
Manual install fails for latest version of Unreal.js-core

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#167]
To reproduce, create a new C++ project with 4.15.1 and do a manual install of Unreal.js

It seems the last working version of Unreal.js-core was your commit https://github.com/ncsoft/Unreal.js-core/commit/4fc66ced6692156bdc8f6b819571b807028b5618 and your mate Hyeoncheol Cho broke things with his last couple of commits:

```
commit 7212a9050d1b14ce7d077cbe0b3dc7fce9631377
Author: ???(Hyeoncheol Cho)(crocuis) <crocuis@ncsoft.com>
Date:   Mon Apr 10 22:31:51 2017 +0900

    fix

commit b8671c76a984d21eecaa66060d4fa9e152570868
Author: ???(Hyeoncheol Cho)(crocuis) <crocuis@ncsoft.com>
Date:   Mon Apr 10 22:22:48 2017 +0900

    fix for IWYU

commit 4fc66ced6692156bdc8f6b819571b807028b5618
Author: Nako Sung <deif79@gmail.com>
Date:   Sat Apr 8 23:03:55 2017 +0900

    Fix #166
```

For anyone else experiencing the same problem, to fix things I did a `git reflog` and `git reset --hard HEAD@{1}` to revert my copy to the last working version I had:

```
Youdaman@DESKTOP-SNUDLCL MINGW64 ~/Desktop/UnrealJS (master)
$ git reflog
7212a90 HEAD@{0}: pull: Fast-forward
4fc66ce HEAD@{1}: clone: from https://github.com/ncsoft/Unreal.js-core

Youdaman@DESKTOP-SNUDLCL MINGW64 ~/Desktop/UnrealJS (master)
$ git reset --hard HEAD@{1}
HEAD is now at 4fc66ce Fix #166
```

**Comment by nakosung** [comment]
@crocuis Please check this problem. :)

**Comment by crocuis** [comment]
I could not reproduce the problem. I want to know more precisely what problems you have. :)

**Comment by Youdaman** [comment]
The problem is that if I update the UnrealJS plugin via git pull it won't build against 4.15, see attached video, which shows that it builds fine for the last change that @nakosung made, but not for the recent changes made by @crocuis -- https://www.youtube.com/watch?v=N0DaTR_y5Kc

**Comment by crocuis** [comment]
@Youdaman fixed. https://github.com/ncsoft/Unreal.js-core/commit/6fbdd8590b7207bfd80d9d04036940747e7fd687

**Comment by Youdaman** [comment]
Thank you @crocuis that fixed it! 😄
