### ISSUE TITLE
Improve Autocomplete docs re VS "Code" (not VS "2015")

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#168]
After trying various things to get Autocomplete working in Visual Studio 2015 I realised that the docs said Code not 2015 -- it might help to put a link to Visual Studio Code https://code.visualstudio.com/

Now I finally have Autocomplete working after all this time (it didn't work properly in VS2015 for me). Even better, it turns out there's several Vim plugins for VSCode like this https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

Anyway, just thought I'd suggest improving the Autocomplete wiki page by being explicit about using Code not 2015 version of Visual Studio in order to get autocomplete working properly (plus it's a cool editor that I didn't even realise existed because I thought Visual Studio 2015 was the only one til I read this http://stackoverflow.com/a/33798601 )

**Comment by nakosung** [comment]
Done. :)

**Comment by Youdaman** [comment]
Nice, I see the Readme has a link now :)

Might also need to update this wiki page https://github.com/ncsoft/Unreal.js/wiki/Autocompletion
