### ISSUE TITLE
Packaged project can't find blueprints?

### ISSUE THREAD

**Issue by timbur** [ncsoft/Unreal.js#171]
In the editor, this works as expected:
```js
const BaseArenaUI = Blueprint.Load('/Game/Blueprints/BaseArenaUI').GeneratedClass;
```

But when the project is packaged, it doesn't work.  This is the error:
```
[2017.06.08-05.59.57:648][  0]LogUObjectGlobals:Warning: Failed to find object 'Blueprint None./Game/Blueprints/BaseArenaUI'
```

I've verified that `Blueprints/BaseArenaUI.uasset` exists within the packaged game content directory.

Also, I'm using 4.15.

**Comment by timbur** [comment]
Never mind.  Apparently the correct string is `'/Game/Blueprints/BaseArenaUI.BaseArenaUI_C'` instead of just `'/Game/Blueprints/BaseArenaUI'`.  I'm really curious as to why the shorter version works in the editor but not in the packaged version.

**Comment by crocuis** [comment]
If you are packaging BP, the BP's GeneratedClass must be included in the cooking process. It is also necessary to modify the code in such a way that it directly access BP's GeneratedClass, not BP.

**Comment by crocuis** [comment]
https://github.com/ncsoft/Unreal.js/wiki/Cooking :)
