### ISSUE TITLE
Loading data tables directly results in no data

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#173]
This _should_ work:

    const dt = DataTable.Load('/Game/tables/detailModels.detailModels');
    const data = dt.GetDataTableRowNames().OutRowNames.map( function( name ){
      return dt.GetDataTableRowFromName( name );
    });

  console.log( JSON.stringify( data, null, 2 ) );

The log is...

    [
      {
        "OutRow": {},
        "$": false
      },
      {
        "OutRow": {},
        "$": false
      },
      {
        "OutRow": {},
        "$": false
      },
      {
        "OutRow": {},
        "$": false
      }
    ]

The "out" from the function call doesn't seem to respect the table's struct? Or am I using this wrong?

**Comment by crocuis** [comment]
It seems to have been modified in 4.16. I did not test it.
https://github.com/EpicGames/UnrealEngine/blob/4.16/Engine/Source/Runtime/Engine/Classes/Kismet/DataTableFunctionLibrary.h#L48

**Comment by mflux** [comment]
Any chance to get a fix on this? ;)

**Comment by crocuis** [comment]
Sorry for the late reply. The function GetDataTableRowFromName you used is a function of type "BlueprintInternalUseOnly", so it can only be used in Blueprint. If you are uncomfortable with blueprints, you'll have to implement those functions in C ++. 
Thanks.
