### ISSUE TITLE
JavascriptPlayground project won't compile/build with 4.16 only 4.17

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#177]
1. follow the installation instructions for the Unreal.js/core/v8 files
2. try to launch JavascriptPlayground via its icon
3. when prompted choose 4.16

The compile/build fails. There's a prompt saying the version of the runtime isn't compatible, and then after that you'll get another prompt saying the build failed.

4.17 builds fine though, however the helloCharacter demo map hangs the editor on Play (see https://github.com/ncsoft/Unreal.js/issues/176)

**Comment by crocuis** [comment]
I'll check :)

**Comment by karlnp** [comment]
Now seeing this with 4.17.1.

**Comment by crocuis** [comment]
https://github.com/ncsoft/Unreal.js/issues/176 Fixed.
