### ISSUE TITLE
Error: TypeError: this.GetCapsuleComponent is not a function

### ISSUE THREAD

**Issue by NicolasDe** [ncsoft/Unreal.js#18]
Hello there, I have been trying to port third-person character over JS and found some weird issue.
I have created ThirdPersonExample class which extends Character, but as soon as I try to get capsule component it gives me an error:

> Error: TypeError: this.GetCapsuleComponent is not a function

```javascript
	function main()
	{
		// declare a new character class
		class ThirdPersonExample extends Character
		{
			// strange? ctor, not constructor...
			ctor()
			{
				// Set size for collision capsule
				this.GetCapsuleComponent().InitCapsuleSize(42.0, 96.0)
```
Maybe I'm doing something wrong?

**Comment by nakosung** [comment]
`GetCapsuleComponent` is not a `UFunction`, so it isn't reflected to Javascript. Instead of using this function, you may refer it directly with `this.CapsuleComponent`.
