### ISSUE TITLE
Root.GetEngine is not a function

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#180]
I'm trying the example in https://github.com/ncsoft/Unreal.js/wiki/Playing-within-editor

Simple script as editortest.js with a javascriptComponent pointing at it and active in editor:

    let editorWorld = Root.GetEngine().GetEditorWorld()
    let actor = new StaticMeshActor(editorWorld)
    let cubeMesh = StaticMesh.Load('/Engine/BasicShapes/Cube')
    actor.RootComponent.SetWorldLocation({Z:123})
    actor.StaticMeshComponent.StaticMesh = cubeMesh

However I get a script error:

`Error: TypeError: Root.GetEngine is not a function`

What is Root supposed to be from?

**Comment by crocuis** [comment]
GetEngine () is not exposed in the JavascriptContext that JavascriptComponent has. The above link (https://github.com/ncsoft/Unreal.js/wiki/Playing-within-editor) explains how to use the Editor Extension, which is configured to automatically run a file with the prefix 'extension'.

**Comment by mflux** [comment]
Got it thanks! When exactly do editor extensions load? As soon as the file exists? Is there a file watcher that the plugin is always running?

**Comment by crocuis** [comment]
When the JavascriptEditorModule is started, create a JavascriptContext and run editor.js in the engine plugin. And editor.js finds and executes extension files.
