### ISSUE TITLE
http request / xhr request

### ISSUE THREAD

**Issue by hasezoey** [ncsoft/Unreal.js#195]
how to make a request? 
i didn't got it from the wiki to work ... ( https://github.com/ncsoft/Unreal.js/wiki/Getting-text-from-HTML )

**Comment by thejustinwalsh** [comment]
```js
let request = require('request.js')
request('GET', 'https://api.ipify.org?format=json').then(result => {
  console.log(JSON.stringify(result, null, 2));
});
```

For more info see `Plugins/UnrealJS/Content/Scripts/request.js`

**Comment by hasezoey** [comment]
Oh, Ok ... i thought request from NPM ...
got it to work.

thanks for the help ^^

(and how to make a POST request with JSON data?)
