### ISSUE TITLE
Console Output

### ISSUE THREAD

**Issue by hasezoey** [ncsoft/Unreal.js#196]
is that normal that some output in the Console is doubled? 
like `console.log('something')` is prints `somethingsomething`

Unreal Engine 4.18
Unreal.js version 0.3.0 (Marketplace Version)

**Comment by can1** [comment]
Same setup, same problem. Also doubles any inputs, example `2+2` prints `2+22+2` and outputs `44`

**Comment by crocuis** [comment]
Fixed. https://github.com/ncsoft/Unreal.js-core/commit/376bdc7bcb8ec53b594ad857826e3033dc7ff665
