### ISSUE TITLE
An explicit Category specifier is required

### ISSUE THREAD

**Issue by HirofumiYoshida** [ncsoft/Unreal.js#217]
In case installing Unreal.js from Marketplace, the following error occurs when compiling the Game.

> Engine/Plugins/Marketplace/UnrealJS/Source/JavascriptGraphEditor/JavascriptGraphEdNode.h(68) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
> Engine/Plugins/Marketplace/UnrealJS/Source/JavascriptGraphEditor/JavascriptGraphEdNode.h(71) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.

UE4 version is 4.19.2.

It seems these error couse from that the following two methods don't have Category.

UJavascriptGraphEdNode :: UpdateSlate()
UJavascriptGraphEdNode :: GetDesiredSize()

**Comment by greywolf001au** [comment]
I am also receiving this error since I created VS source for my project, now I cannot compile or reopen my project :(

**Comment by greywolf001au** [comment]
Wow github was slow to send the email for this comment, thank you I will try to repair my project over the weekend :)
