### ISSUE TITLE
can't compile GWorld.CreateWidget in typescript

### ISSUE THREAD

**Issue by kmu1205** [ncsoft/Unreal.js#224]
when i attempt to call GWorld.CreateWidget in typescript, a compilation error occurs. 
This is because GWorld does not have a function 'CreateWidget'. 

How do you solve this?
(JavaScript is fine, but only occur in typescript)

**Comment by johnathandinh** [comment]
You need to update the typings and add this function to the Gworld class

**Comment by kmu1205** [comment]
i resolve this problem. so close this issue
