### ISSUE TITLE
[question] Can all JavascriptComponent share one isolate or even on context?

### ISSUE THREAD

**Issue by marynate** [ncsoft/Unreal.js#23]
So  each JavascriptComponent has it's own isolate and context, I'm curious why can't they share one isolate, or even share one same context?

**Comment by nakosung** [comment]
`JavascriptComponent` is not a only form which can uses `JavascriptContext` and `JavascriptIsolate`. It may be possible to make `JavascriptComponent` to share "virtual shared context", but I think that there is no good reason to do that. Having many components are not good for the engine.

Maybe `JavascriptComponent` is needed to be invisible for programmers.

**Comment by marynate** [comment]
Hi nakosung, thanks for your answer!

"Having many components are not good for the engine." Do you mean JaascriptComponent or Generic unreal component is too expensive?
