### ISSUE TITLE
ListView : There is no EntryWidgetClass specified on this list

### ISSUE THREAD

**Issue by hamkoo** [ncsoft/Unreal.js#232]
When use the code : UMG(ListView,{})
I got the message : There is no EntryWidgetClass specified on this list. Even if doing custom stuff, this is always required as f fallback.
How should i do? tks!

**Comment by crocuis** [comment]
```
UMG(JavascriptListView, {EntryWidgetClass = JavascriptUserObjectListEntry })
```

**Comment by hamkoo** [comment]
@crocuis Thanks for your advice.
The message is still exist with follow code:
UMG(JavascriptListView, {EntryWidgetClass  :  JavascriptUserObjectListEntry })

As your advice , it's done with the follow:
class MyListView extends JavascriptListView {
    ctor() {
        this.EntryWidgetClass = JavascriptUserObjectListEntry
    }
}
let MyListView_C = uclass(MyListView)

**Comment by hamkoo** [comment]
Anyone can give a demo about JavascriptTileView?

class MyListView extends JavascriptTileView {
ctor() {
this.EntryWidgetClass = MyItem_C
}
}
let MyListView_C = uclass(MyListView)
UMG(MyListView_C,{OnGenerateRowEvent:(item, column)=>{}})

With above code i got the message : Please specify an OnGenerateTile

@crocuis Could you give me any advice about JavascriptTileView?

**Comment by keicoon** [comment]
you would better close this issue that is duplicated in "https://github.com/ncsoft/Unreal.js/issues/234"

**Comment by hamkoo** [comment]
Now, it's ok as follow:
>UMG(
    JavascriptListView,
    $link:elem => {
        elem.JavascriptContext = Context
        elem.EntryWidgetClass = WidgetBlueprint.Load('/Game/Test/EntryWidget_C').GeneratedClass
    }
)
