### ISSUE TITLE
How to use JavascriptTileView

### ISSUE THREAD

**Issue by hamkoo** [ncsoft/Unreal.js#234]
Anyone can give a demo about JavascriptTileView?

class MyItem extends JavascriptUserObjectListEntry {
	ctor() {
		console.log('MyItem...')
	}
}
let MyItem_C = uclass(MyItem)

class MyListView extends JavascriptTileView {
	ctor() {
		this.EntryWidgetClass = MyItem_C
	}
}
let MyListView_C = uclass(MyListView)
UMG(MyListView_C,{OnGenerateRowEvent:(item, column)=>{}})

With above code  i got the message : Please specify an OnGenerateTile

**Comment by crocuis** [comment]
JavascriptTileView does not support delegates that generate Widgets per Column, such as OnGenerateRowEvent.

**Comment by hamkoo** [comment]
![image](https://user-images.githubusercontent.com/321692/50948607-0030bc80-14de-11e9-8e47-e245962b5958.png)
I get the result with blueprint above, so how to do with unreal.js?
![image](https://user-images.githubusercontent.com/321692/50948638-26eef300-14de-11e9-8c11-98844903b89d.png)

**Comment by crocuis** [comment]
```
UMG(JavascriptTileView, {$link: elem => elem.AddItem(...) });
```

**Comment by hamkoo** [comment]
![image](https://user-images.githubusercontent.com/321692/52159739-7ee6d700-26e3-11e9-9046-b9d9405b085d.png)
There is still show the message.

@crocuis Could you give a detail code, thanks!

**Comment by keicoon** [comment]
Give me your code snippet to check problem.

**Comment by hamkoo** [comment]
The code in JavascriptTileView.cpp:

TSharedRef<STableViewBase> UJavascriptTileView::RebuildListWidget()
{
	MyTileView = SNew(STileView< UObject* >)
		.SelectionMode(SelectionMode)
		.ListItemsSource(&ListItems)
		.ItemHeight(EntryHeight)
		.OnGenerateTile(BIND_UOBJECT_DELEGATE(STileView< UObject* >::FOnGenerateRow, HandleOnGenerateTile))

...
}

now, the message "Please specify an OnGenerateTile" go away after ".OnGenerateTile(BIND_UOBJECT_DELEGATE(STileView< UObject* >::FOnGenerateRow, HandleOnGenerateTile))" added

**Comment by hamkoo** [comment]
![image](https://user-images.githubusercontent.com/321692/59975211-2196e800-95e8-11e9-8a5a-7d6ddaa8f81a.png)
