### ISSUE TITLE
Custom module resolution

### ISSUE THREAD

**Issue by Dmerle** [ncsoft/Unreal.js#235]
I've been working on a virtual file system for easier organization and importing of many different kinds of user generated content. I'd like for 'require()' to be able to use these virtual paths when loading modules.

The following should be able to add this behaviour in Node:
```
import { RequestFilePath } from './ModulePath';
import Module = require('module');

export function OverrideLoad() {
    var OriginalLoad = Module._Load;

    Module._Load = function (request: string, parent, isMain) {
        request = RequestFilePath(request);

        return OriginalLoad(request, parent, isMain);
    }
}
```
But unfortunately, it would seem that require works quite differently in Unreal.js. Is there any way that I can achieve this? Perhaps using C++?

**Comment by crocuis** [comment]
The require of unreal.js is made similar to node.js, and if you handle it in a separate function, not require, you can achieve the desired goal.

**Comment by keicoon** [comment]
How about you read "require" function that be written in "uneal.js.core"? It make you comprehend.
I give you that [file link](https://github.com/ncsoft/Unreal.js-core/blob/4ca174f51857f5f5ff43e84d50b33f3f027a54a3/Source/V8/Private/JavascriptContext_Private.cpp) and line : 1687.

**Comment by Dmerle** [comment]
I actually already solved this by adding a delegate to that file which takes the requested path and replaces it with a modified path, which is evaluated in javascript. I'll close this now.
