### ISSUE TITLE
Question : Can I use Unreal.js to make a complex game ?

### ISSUE THREAD

**Issue by Zbluu** [ncsoft/Unreal.js#238]
Hello,

I would like to know if this plug-in can totally replace C++ programming, for example, to create a game.
If I make a game with only Javascript, the performances will be substantially the same as a game made in C++ ?
I would like to know the limits of this plug-in before converting all my C++ code to Javascript.

Sorry if this question has already been asked, but I didn't find explicit information about this.

**Comment by crocuis** [comment]
Just as you can create games with Blueprint, you can create games with just Javascript. Please note that Unreal.js was not created to replace C ++, but to replace Blueprint.
Unreal.js may perform better than Blueprint, but it is not comparable to C ++.

**Comment by Zbluu** [comment]
Thanks for your answer.

I tried Unreal.js and it's an amazing plug-in.
I just regret that it's not compatible with all NodeJS packages, like socket.io.
(For those interested, you can use this plug-in https://github.com/getnamo/socketio-client-ue4 as an alternative)
