### ISSUE TITLE
[question] OS X support

### ISSUE THREAD

**Issue by ribbedcrown** [ncsoft/Unreal.js#24]
Are you planning OS X or Unix support?

P.S. Great work! This plugin looks very promising.

**Comment by nakosung** [comment]
I'm using os x and linux for programming other projects, but currently I'm developing UnrealEngine apps only within Windows environment. Android is already being supported(thanks to @marynate).

**Comment by ribbedcrown** [comment]
Glad to hear, I'm not so familiar with C/C++, but maybe i can help with something?

**Comment by nakosung** [comment]
Could you try to build with those platforms?

**Comment by nakosung** [comment]
This thread seems dead.
