### ISSUE TITLE
[Question] Multithreading / Async tasks

### ISSUE THREAD

**Issue by Zbluu** [ncsoft/Unreal.js#244]
I have a function that spawns complex ProceduralMeshComponent on runtime and, each time the function is executed, the game lag and freeze during 1-2sec (the time to calculate and spawn the new ProceduralMeshComponent).

I would like to know if there is a way to execute a function in another thread to not "block" the game main thread, or maybe if there are async tasks that can do the same.
It seems possible in C++, so what about Unreal.js ?

**Comment by johnathandinh** [comment]
Javascript only has 1 thread, but it can run async. Just use async/await.

**Comment by Zbluu** [comment]
I already tried with async/await, and the result it the same : the generated mesh causes the game freezing. This is what i tried : 
```
function generate_one_mesh(){
    return new Promise(function(resolve) {
        const generated_mesh = new Actor(GWorld);
        // Generate mesh here...
        generated_mesh.load();
        resolve();
    })
}

async function main() {
    generate_one_mesh();
}

main()
```
I do not use await because I don't need to wait until the mesh is generated.

Yes, multithreading is not possible in Javascript, but maybe the Unreal.js API can do it, I just ask because I can not found documentation about this.

**Comment by Zbluu** [comment]
See #246.
