### ISSUE TITLE
AsyncTask crash

### ISSUE THREAD

**Issue by Zbluu** [ncsoft/Unreal.js#246]
So, following my idea to do async tasks like I said it on #244 , I have implemented FAsyncTask in c++ using [this tutorial](https://wiki.unrealengine.com/Using_AsyncTasks?fbclid=IwAR1uRUxGVteOtDW1poAtjTWmtsUdhZXH3d2ploocS7n7GwGEuaajNpX4zQc).

I'm trying to implement FAsyncTask that will execute JavaScript code in a background thread.
So this is my file TestTask.h where all the C++ code is located : 

```C++
#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "Async/AsyncWork.h"
#include "TestTask.generated.h"

// =============================================
// Object that is inherit in JS.
UCLASS(Blueprintable, BlueprintType)
class UTaskObject : public UObject{
    GENERATED_BODY()
public:

  UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
  void OnSomething();
  void OnSomething_Implementation() {
    UE_LOG(LogTemp, Warning, TEXT("HELLO WORLD"));
  }

};

// =============================================
// Task that will execute UComponentA.OnSomething() in a background thread.
class MultithreadedTask : public FNonAbandonableTask {
public:
  MultithreadedTask(UTaskObject* object){
    this->object = object;
  }
  UTaskObject* object;

  FORCEINLINE TStatId GetStatId() const
  {
    RETURN_QUICK_DECLARE_CYCLE_STAT(MultithreadedTask, STATGROUP_TaskGraphTasks);
  }

  void DoWork()
  {
    // Executed on background thread :
    object->OnSomething();
  }
};

// =============================================
// Static function used to create a task.
UCLASS()
class ENDLESS_CLIENT_API UMultithreadedLibrary : public UBlueprintFunctionLibrary {
  GENERATED_BODY()

public:
  UFUNCTION(BlueprintCallable)
  static void CreateTask(UTaskObject* object) {
    (new FAutoDeleteAsyncTask<MultithreadedTask>(object))->StartBackgroundTask();
  }
};
```

This is very simple to use in JavaScript : 
```JavaScript
const test_task = new TaskObject();
MultithreadedLibrary.CreateTask(test_task);
```

This code works, the editor print "HELLO WORLD" because I don't override the OnSomething() function.
But now, if I override this function of the TaskObject class like this : 
```JavaScript
const uclass = require('uclass')().bind(this,global);
class TaskObjectChild extends TaskObject {
  OnSomething(){
    console.log('This is JavaScript.')
  } 
}

const TaskObjectChild_C = uclass(TaskObjectChild);
const test_task = new TaskObjectChild_C();
MultithreadedLibrary.CreateTask(test_task);
```

The editor is instantly closed without print debug crash logs (and nothing is written in the log and crash log files).
I tested many different workarounds these last days (like to execute Delegate, FJavascriptFunction, ...) and all of these do the same things. Sometimes, I have ACCESS_VIOLATION errors, but it doesn't help me.
Any idea ?

**Comment by johnathandinh** [comment]
Bind JS to Entt lib? That would be...sweet.

**Comment by Dmerle** [comment]
If I'm not mistaken, when you do that you're essentially passing a javascript delegate from the main thread to the new thread which is not thread-safe (meaning that it would try to call the function on the main thread, which will cause problems if the main thread is already busy). I would recommend using a TQueue to queue up data from the task, then check for new entries each tick on the main thread where your javascript is. I don't think there's any way to execute javascript on a seperate thread.

**Comment by Zbluu** [comment]
Thank you for taking the time to answer me.
This is also the conclusion I deduced from it : this method is not thread-safe.
Maybe it can work with a TQueue system, but that's not exactly what I'm looking to do.

Multithreading seems not possible with Unreal.js, so I can close this thread.
For all those who will read this thread, I advise you to do multithreading in C++ or BP, but don't mix it with Unreal.js.
