### ISSUE TITLE
Access Parent Blueprint Variable from JS

### ISSUE THREAD

**Issue by Dejon** [ncsoft/Unreal.js#247]
Are Unreal.js modules aware of their parent actor? I'm trying to manipulate a public Blueprint-defined variable from js, which is a component of the blueprint. Is this possible, or does the js module have no knowledge of its owner?

**Comment by keicoon** [comment]
if you want to manipulate bp-variable in js, access like object property. it is working in js.
example)
```
var something = new your_bp_C(); // bp_c has some public variable and spawn in script
something.A = 'asd'
var a = something.A // a would be set by 'asd'
```

**Comment by Dejon** [comment]
That works! Thanks for your help.
