### ISSUE TITLE
Now, it's support for inheritance from JS class?

### ISSUE THREAD

**Issue by hamkoo** [ncsoft/Unreal.js#249]
Now, it's support for inheritance from JS class?

[https://github.com/ncsoft/Unreal.js/issues/76](https://github.com/ncsoft/Unreal.js/issues/76)

There is still the error info : TypeError: Instance.test is not a function.

uclass.js:
>klass = CreateClass(className, {
                    Parent: parentClass,
                    Functions: proxy,
                    ClassFlags: classFlags,
                    Outer: thePackage,
                    NonNative: nonNative,
                    Properties: includeProperty ? properties : []
                });

JavascriptContext_Private.cpp:
>global->Set(V8_KeywordString(isolate(), "CreateClass"), FunctionTemplate::New(isolate(), fn, self)->GetFunction());

>auto ParentClass = UClassFromV8(isolate, Opts->Get(I.Keyword("Parent")));

above code, it'll skip the parentClass and return an UClass

**Comment by crocuis** [comment]
Show me your entire code. I do not understand the context. If you have questions about subclassing, see https://github.com/ncsoft/Unreal.js/wiki/Subclassing.

**Comment by hamkoo** [comment]
@crocuis thanks for your reply!~
My question is same with : https://github.com/ncsoft/Unreal.js/issues/76  (Parent functions not accessible from subclass instance?)

    class MySMA extends StaticMeshActor {
        ctor() {
             this.StaticMeshComponent.SetStaticMesh(StaticMesh.Load('/Engine/BasicShapes/Cube.Cube'))
        }

        test() {
            console.log("Test")
        }
    }

    class MySubSMA extends MySMA {
        constructor() {
            super()
        }

        ctor() {
            super.ctor()
            this.StaticMeshComponent.SetStaticMesh(StaticMesh.Load('/Engine/BasicShapes/Cube.Cube'))
        }
        // if I uncomment this, both test functions will be called, as expected
        // test() { 
        //     super.test()
        //     console.log("Test")
        // }
    }

    let MySubSMAClass = Utils.Compile(MySubSMA)
    let Instance = new MySubSMAClass(Utils.GetWorld(), {X:0})
    Instance.test() // throws an error: test is not defined!

There is the message: test is not defined!
I debugged unreal.js with c++ code ,  find it'll skip the parent class defined with js and return an UClass with c++ .

**Comment by keicoon** [comment]
How about register parent class to class first?
```
// TODO: call "MySMA" by uclass
let MySMAClass = require('uclass')()(global, MySMA)
let MySubSMAClass = require('uclass')()(global, MySubSMA)
```
Let me know your result :)

**Comment by hamkoo** [comment]
> How about register parent class to class first?
> 
> ```
> // TODO: call "MySMA" by uclass
> let MySMAClass = require('uclass')()(global, MySMA)
> let MySubSMAClass = require('uclass')()(global, MySubSMA)
> ```
> 
> Let me know your result :)

Thanks for your reply.

let MySMAClass = require('uclass')()(global, MySMA)
let MySubSMAClass = require('uclass')()(global, MySubSMA)

Hierarchy of define with above code:
MySMA extends StaticMeshActor 
MySubSMA extends MySMA extends StaticMeshActor 

Hierarchy after require('uclass'):
MySMAClass extends StaticMeshActor 
MySubSMAClass extends StaticMeshActor

so, the functions of MySMA will be lost.

**Comment by hamkoo** [comment]
Now, the question has been resolved with a traceClass function added in uclass.js.

download : [uclass.zip](https://github.com/ncsoft/Unreal.js/files/3159837/uclass.zip)

The function named traceClass will trace the parent until 'StaticClass'.

function traceClass(template)
{
    let list = Object.getOwnPropertyNames(template);
    let index = list.findIndex((e)=>(e == 'StaticClass'));
    if(index>-1){
        return;
    }

    _(Object.getOwnPropertyNames(template.prototype)).filter((name) => {
        let c = Object.getOwnPropertyDescriptor(template.prototype, name);
        return (c.get || c.set) == undefined;
    })
    .forEach((k) => {
        if (k == "properties") {
            let func = String(template.prototype[k])
            func = func.substr(func.indexOf('{')+1)
            func = func.substr(0, func.lastIndexOf('}'))
            func = _.compact(func.split('\n').map((l) => l.trim())).map((l) => {
                if (l.indexOf("this.") != 0) return
                l = l.substr(5)
                return refactored(l)
            })
            properties = _.merge(properties, func)
        } else if (k != 'constructor') {
            if(proxy[k] === undefined){
                let F = proxy[k] = template.prototype[k]    
                let s = String(F)        
                let matches = RE_func.exec(s)
                if (!matches) throw "invalid function " + k

                let functionName = matches[1]
                s = matches[4]
                let a = (s || '').split(/[\[\],]/).map((x) => x.trim())
                a = _.compact(a)
                let flags = _.filter(a, (a) => /^[\-\+]/.test(a))
                a = _.filter(a, (a) => !/^[\-\+]/.test(a))
                let args = ((matches[2] || '').split(',').map((x) => refactored(x.trim())))
                F.IsUFUNCTION = false
                if (_.every(args, (x) => !!x)) {
                    F.Signature = args
                    F.IsUFUNCTION = true
                }

                F.Decorators = a
                if (a.length > 0) {
                    F.IsUFUNCTION = true
                }
                if (/Binding$/i.test(a[0])) {
                    F.IsUFUNCTION = true
                    let prefix = a[0].substr(0, a[0].length - 7)
                    let pattern = inputbinding_patterns[prefix]
                    if (!pattern) throw "Invalid binding pattern"

                    let binding = {
                        type: prefix,
                        FunctionNameToBind: functionName
                    }
                    flags.forEach((flag) => {
                        binding[flag.substr(1)] = (flag[0] == '+')
                    })
                    bindings.push(_.extend(binding, pattern(a)))
                }
            }                       
        }
    })
    traceClass(template.__proto__);
}

traceClass(template);

**Comment by hamkoo** [comment]
Example:

        class A extends JavascriptWidget{

            OnInitialized(){
                let btn = new Border(this);
                let txt = new TextBlock(this);
                txt.SetText('uclass btn');
                btn.AddChild(txt);
                this.SetRootWidget(btn);
            }

            OnMouseButtonDown(MyGeometry: Geometry,MouseEvent: UPointerEvent){
                console.log('A.OnMouseButtonDown');
                return super.OnMouseButtonDown(MyGeometry, MouseEvent);
            }

            OnMouseEnter(MyGeometry: Geometry,MouseEvent: UPointerEvent){
                console.log('A.OnMouseEnter');
                return super.OnMouseEnter(MyGeometry, MouseEvent);
            }
            
        }

        class B extends A {

            OnMouseButtonDown(MyGeometry: Geometry,MouseEvent: UPointerEvent){
                console.log('B.OnMouseButtonDown');
                return super.OnMouseButtonDown(MyGeometry, MouseEvent);
            }

            OnMouseEnter(MyGeometry: Geometry,MouseEvent: UPointerEvent){
                console.log('B.OnMouseEnter');
                // return super.OnMouseButtonUp(MyGeometry, MouseEvent);
            }
        }

        let B_C = require('uclass')()(global, B, true, null, true);
        let b = new B_C(this);

b.OnMouseButtonDown>>
B.OnMouseButtonDown
A.OnMouseButtonDown


b.OnMouseEnter>>
B.OnMouseEnter

**Comment by crocuis** [comment]
Fixed. 08d3e9443cd9c5faf988d5a61cffb2ed2e2a687e
