### ISSUE TITLE
let process= require('child_process')  but return undefined

### ISSUE THREAD

**Issue by hamkoo** [ncsoft/Unreal.js#254]
var process = require('child_process');
        var file = process.spawn('curl', ['http://xxx/app.js']);
        var fdata = '';
        file.stdout.on('data', function (data) {    
            fdata = fdata + data;
        });
        file.stdout.on('end', function (data) {   
            console.log(fdata);
        });

process is undefined

**Comment by crocuis** [comment]
Because unreal.js is not node.js, node.js based api is not available.

**Comment by hamkoo** [comment]
@crocuis  tks! node.js will be embedded ?

**Comment by crocuis** [comment]
We do not consider embedding node.js, and we can add api-like functionality provided by node.js to C ++ code in unreal.js.

**Comment by hamkoo** [comment]
thanks!
