### ISSUE TITLE
Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().

### ISSUE THREAD

**Issue by hamkoo** [ncsoft/Unreal.js#256]
After replace with v8 7.5.288 , the error will show  while running the code:  Template->PrototypeTemplate()->Set(static_class, I.External(StructToExport));
![image](https://user-images.githubusercontent.com/321692/61173791-c050ac00-a5ca-11e9-9714-3da3c1c8d322.png)

![image](https://user-images.githubusercontent.com/321692/61191945-c5088380-a6e2-11e9-8472-9f9a3bb1ae5b.png)

**Comment by hamkoo** [comment]
Any changed in v8 code? @crocuis

**Comment by crocuis** [comment]
unreal.js uses the modified v8 and runs on the 7.4.288 build. If you want to update your v8 version, you can find a history of https://github.com/ncsoft/v8/tree/7.4.288.9999.

**Comment by hamkoo** [comment]
tks for your reply @crocuis
