### ISSUE TITLE
Is it possible to initialize a UJavascriptContext not on the Main thread?

### ISSUE THREAD

**Issue by nickfrev** [ncsoft/Unreal.js#259]
I'm not initializing the UJavascriptContext when the game begins. I am starting it on a trigger (Such as a user touching a block). Doing this I've noticed a large pause of about 1-2 seconds when calling the below code. I've tried to initialize the Context in a thread and pass it back to the main thread when it's finished but that causes an Access violation error. The code runs fine in the main thread.

The chunk of code I'm testing with:
```cpp
UJavascriptIsolate* Isolate = nullptr;
Isolate = NewObject<UJavascriptIsolate>();
Isolate->Init(false);
Isolate->AddToRoot();
auto* Context = Isolate->CreateContext();
```

Is there a way to do this properly? 

My current set-up:
I started a fresh project using the C++ First Person Template. I have added a single custom class (Source Code below). I attach this class to a cube with a contact trigger. When triggered the custom class calls LoadJSIsolate(). There is a boolean to toggle between loading on the main thread and loading on a secondary thread. When run on the main thread, everything works. When running in a secondary thread it throws an Access violation error: 

```
Unhandled exception at 0x00007FF87DCD156E (UE4Editor-V8.dll) in UE4Editor.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

Code:
**Spell.h**
```cpp
// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "JavascriptIsolate.h"
#include "JavascriptComponent.h"
#include "IV8.h"
#include "Spell.generated.h"


UCLASS( ClassGroup=(Custom), meta=(BlueprintSpawnableComponent) )
class SPELLCRAFT_API USpell : public UActorComponent
{
	GENERATED_BODY()

public:	
	// Sets default values for this component's properties
	USpell();

	FAsyncTask<class JavascriptIsolateGeneratorTask>* LoadJSEngineAsyncTask;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool Main_Thread;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UJavascriptContext *Source_Context;

	UFUNCTION()
	void CatchEngineIsolates(UJavascriptContext* SourceContext);

protected:
	// Called when the game starts
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	UFUNCTION(BlueprintCallable, Category = "Components")
	void LoadJSIsolate();
};

//==========================
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FLoadJSEngine_IsolatePass, class UJavascriptContext*, SourceContext);
class JavascriptIsolateGeneratorTask : public FNonAbandonableTask {
private:

public:
	JavascriptIsolateGeneratorTask();
	~JavascriptIsolateGeneratorTask();

	FLoadJSEngine_IsolatePass IsolatePass;

	// required by UE4
	FORCEINLINE TStatId GetStatId() const {
		RETURN_QUICK_DECLARE_CYCLE_STAT(JavascriptIsolateGeneratorTask, STATGROUP_ThreadPoolAsyncTasks);
	}

	void DoWork();
};
```

**Spell.cpp**
```cpp
// Fill out your copyright notice in the Description page of Project Settings.

#include "Spell.h"
#include "JavascriptIsolate.h"
#include "JavascriptContext.h"
#include "IV8.h"

// Sets default values for this component's properties
USpell::USpell()
{
	// Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
	// off to improve performance if you don't need them.
	PrimaryComponentTick.bCanEverTick = true;

	Main_Thread = true;
	// ...
}

// Called when the game starts
void USpell::BeginPlay()
{
	Super::BeginPlay();

	// ...
	
}


// Called every frame
void USpell::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// ...
}

void USpell::CatchEngineIsolates(UJavascriptContext* SourceContext) {
	this->Source_Context = SourceContext;

	UE_LOG(LogTemp, Warning, TEXT("Secondary Thread JS Context Done"));
}

void USpell::LoadJSIsolate() {
	if (Main_Thread) {
		UJavascriptIsolate* Isolate = nullptr;
		Isolate = NewObject<UJavascriptIsolate>();
		Isolate->Init(false);
		auto* Context = Isolate->CreateContext();
		UE_LOG(LogTemp, Warning, TEXT("Main Thread JS Context Done"));
	} else {
		LoadJSEngineAsyncTask = new FAsyncTask<JavascriptIsolateGeneratorTask>();
		LoadJSEngineAsyncTask->GetTask().IsolatePass.AddDynamic(this, &USpell::CatchEngineIsolates);
		LoadJSEngineAsyncTask->StartBackgroundTask();
		UE_LOG(LogTemp, Warning, TEXT("Task Started"));
	}
}

//==========================

JavascriptIsolateGeneratorTask::JavascriptIsolateGeneratorTask() {
}

JavascriptIsolateGeneratorTask::~JavascriptIsolateGeneratorTask() {
	UE_LOG(LogTemp, Warning, TEXT("Task Finished"));
}

void JavascriptIsolateGeneratorTask::DoWork() {

	UE_LOG(LogTemp, Warning, TEXT("Do Work - Start"));

	UJavascriptIsolate* Isolate = nullptr;
	Isolate = NewObject<UJavascriptIsolate>();
	Isolate->Init(false);
	UJavascriptContext* Context = nullptr;
	Context = Isolate->CreateContext();
	
	UE_LOG(LogTemp, Warning, TEXT("Do Work - End"));

	// Broadcast Delegate
	IsolatePass.Broadcast(Context);
}
```

**Comment by crocuis** [comment]
Have you created multiple isolates in the main thread?

**Comment by drfrev** [comment]
I'm currently only working with the one isolate at the moment.

For a little more info: To test this out, I'm working with a clean version of the first person C++ template and the only custom code I am running is that single block of code either inside the main thread or in a secondary thread.

**Comment by nakosung** [comment]
There might be some pieces of code which runs on main thread to process timer things and so on. If you want to tick your isolate within other threads, I think the codes I mentioned should be guarded or off-loaded to other threads for thread safety.

**Comment by getnamo** [comment]
Just wanted to comment that this is indeed possible if you get rid of things like bootstrap and un-expose modules. I've been tinkering a bit with multi-threading, have some ideas to make it quite seamless in theory.

**Comment by nickfrev** [comment]
I closed the issue because I realized that my use case for unrealjs is not in line with it's intended use case.

I have still been playing with making it work in threads. For my use case, a completely clean javascript context with nothing ue4 exposed to it is perfect. I saw that there are some exposes when you create a context (specifically the exposure of the context). I have currently just been creating a pool of JS Contexts during startup and then choosing from those at runtime to avoid the runtime hiccup.

Ultimately I don't think I know the Unreal environment well enough yet to get it working 100%.

**Comment by getnamo** [comment]
Don't have an ETA yet, but if you're brave you can follow the changes in this feature branch: https://github.com/getnamo/Unreal.js-core/tree/feature-enhanced-exposure-control

I'm aiming to do three things via fairly opinionated changes:
1. Add a feature/permission based system for exposing things to V8 js components. This means closer to how phone apps and web browsers can incrementally ask for features. In my use case I can see running main thread contexts or multithreaded instances without access to unreal except via specific means to stop scripts from top easily crashing the game (or limit what they can do)
2. Multithreading. Similar to your idea of a pool you can ask for a background thread to do work without impacting game thread.
3. Do 2) in a serializable lambda callback on main thread. You specify a function and object data, it will serialize both, call on background thread and return results reserialized on calling thread. This is the experimental idea but I think it should be possible and will make it pretty easy to offload tasks.

**Comment by nickfrev** [comment]
I will definitely be looking into that. I'm sure you have many of the issues I've been running into figured out in your branch. Also, all of those features you're looking to add have a huge amount of value in them.

**Comment by getnamo** [comment]
@eoware

My feature branch got merged in my own fork and I'm keeping it up to date here: https://github.com/getnamo/Unreal.js-core/commits/master. Core parts of the multithreaded system is here: https://github.com/getnamo/Unreal.js-core/blob/master/Source/V8/Public/JavascriptAsync.h and https://github.com/getnamo/Unreal.js-core/blob/master/Content/Scripts/async.js along with https://github.com/getnamo/Unreal.js-core/blob/master/Source/V8/Public/JavascriptInstanceComponent.h and https://github.com/getnamo/Unreal.js-core/blob/master/Source/V8/Public/JavascriptInstance.h for more fine-grained exposure control required to make this work.

I ended up with an Async module type system with multi-threaded inline js, example found here: https://twitter.com/getnamo/status/1276977110762979328. Basically you can pass a callback into a function and this callback will run on a separate context and thread. Any functions passed in as a parameter will be callable from that thread as an async variant which allows for pinning and easy transparent thread communication. Essentially this adds something akin to C++11 lambdas to unreal.js with a bit more dev-friendly usability. I did also implement the exposure control system: https://twitter.com/getnamo/status/1271772156611817472 this should make it easier to make much lighter javascript instances (e.g. with isolate and/or context re-use) and with safer execution by only including features you need/allow exposure.

Still need to make a new module/package system before I consider my branch is feature complete, more recent work will be tracked here: https://github.com/getnamo/Unreal.js-core/tree/feature-umodule.

The changes I make to unreal.js are fairly opinionated so I'm not convinced they belong in mainline. That said you can find lighter weight javascript instances (with feature control and context re-use) and async multi-threading working if you're looking for them.

**Comment by eoware** [comment]
@getnamo
"That said you can find lighter weight javascript instances (with feature control and context re-use) and async multi-threading working if you're looking for them."

So I am very new to Unreal development, and thought finding something that already integrates was important, but the javascript execution like I'd like to do really is something that will need to be coded in anyway, right, so unreal.js may just be overkill?

**Comment by getnamo** [comment]
Depends on what you want to do. If for example you want a js api that you define, you could e.g. expose the 'Root' module on a JavascriptInstanceComponent. This will only expose the JavascriptInstanceComponent functions to js and you can use that to get e.g. Owner (the blueprint that contains the component) via ```const Owner = Root.GetOwner()``` and call it's exposed blueprint functions there (e.g ```Owner.MySpecialFunction('some data')```). It would be fairly trivial to wrap this up in a way that would be clean so that users can call an API you define. You can largely do the same with vanilla unreal.js JavascriptComponents, but they'll also have the whole engine api exposed and accessible from the javascript side.

It's unlikely you can get everything working just right out of the box, so some coding to get things the way you want is needed, but that's almost always the case. Best way to know if you're going down the right path is to define precisely what you need it to do and compare with the current capabilities vs what needs to be added.

**Comment by eoware** [comment]
Thanks, this is exactly the initial direction I think I needed to do it the 'unreal' way. And I am kind of kidding myself and probably overanalyzing trying to limit the API, at least initially, because I am mainly working on this to enhance an existing game with a mod mostly for my own purposes. If it ever gets to the point where I might want to publish it, I can refactor to limit what gets exposed. Having the full API exposed initially will actually be better for dev/debug purposes.
