### ISSUE TITLE
UObject.Find is not a function

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#26]
Hi Nako, I've updated to the latest version and encountered this problem:

    Error: TypeError: UObject.Find is not a function
    Error:     at register (C:\Program Files (x86)\Epic Games\4.10\Engine\Plugins\UnrealJS\Content\Scripts\uclass.js:57:30)
    Error:     at compile (C:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/cpcsruntime.js:10:20)

UnrealJS exists here: C:\Program Files (x86)\Epic Games\4.10\Engine\Plugins\UnrealJS

Which I've unzipped from UnrealJS.Prebuilt.4.10.1-20160106-1

The line from which eventually reaches that is:

    function compile( cl ){
      return uclass()( global, cl );
    }

Which I've copied from one of your examples.

**Comment by mflux** [comment]
I switched back to UnrealJS.Prebuild.4.10-hotfix-20151127-1 and it appears to have fixed the issue. I assume something is wrong with the newer build?

**Comment by nakosung** [comment]
I rebuilt and uploaded a new build, please check again with the new build. (Unfortunately there is no automated test yet)

**Comment by mflux** [comment]
Hi Nako, thanks for the new build. I've tried it again and am getting the same issue.

Is it something with my install that's incorrect? Content/Scripts should be in the Plugins folder, and then what else should be in my game's Content/Scripts folder?

**Comment by nakosung** [comment]
There should be 'aliases.js' in GameContent/Scripts. 

```
        Context.WriteAliases(Context.Paths[0] + 'aliases.js')

        Context.RunFile('aliases.js')
        Context.RunFile('polyfill/unrealengine.js')
        Context.RunFile('polyfill/timers.js')
```

:)

**Comment by mflux** [comment]
I do have that. One thing I noticed that was a source of confusion was that there are two Content/Scripts folders, one in the Plugin/UnrealJS and the other in Plugin/UnrealJS/Examples

![screenshot 2016-03-03 17 26 23](https://cloud.githubusercontent.com/assets/1041360/13515304/1a49d5f2-e165-11e5-9207-a3d2cdb7a11d.png)

What I did in the previous version was I copied the working example files in Content/Scripts folder to my project's Content/Scripts folder and then started building from there. Am I doing this correctly?


Where is this:

        Context.WriteAliases(Context.Paths[0] + 'aliases.js')

        Context.RunFile('aliases.js')
        Context.RunFile('polyfill/unrealengine.js')
        Context.RunFile('polyfill/timers.js')

Supposed to be?

**Comment by mflux** [comment]
I see now where the Context.RunFile is (bootstrap). However the aliases.js seem to be missing UObject.prototype.Find

UObject.prototype.Modify = UObject.prototype.ModifyObject;
UObject.prototype.ClearTimerbyFunctionName = UObject.prototype.K2_ClearTimer;
UObject.prototype.GetTimerElapsedTimebyFunctionName = UObject.prototype.K2_GetTimerElapsedTime;
UObject.prototype.GetTimerRemainingTimebyFunctionName = UObject.prototype.K2_GetTimerRemainingTime;
UObject.prototype.IsTimerActivebyFunctionName = UObject.prototype.K2_IsTimerActive;
UObject.prototype.IsTimerPausedbyFunctionName = UObject.prototype.K2_IsTimerPaused;
UObject.prototype.PauseTimerbyFunctionName = UObject.prototype.K2_PauseTimer;
UObject.prototype.SetTimerbyFunctionName = UObject.prototype.K2_SetTimer;
UObject.prototype.DoesTimerExistbyFunctionName = UObject.prototype.K2_TimerExists;
UObject.prototype.UnpauseTimerbyFunctionName = UObject.prototype.K2_UnPauseTimer;
UObject.prototype.ToString = UObject.prototype.Conv_ObjectToString;
UObject.prototype.Equal = UObject.prototype.EqualEqual_ObjectObject;
UObject.prototype.NotEqual = UObject.prototype.NotEqual_ObjectObject;
UObject.prototype.GetClass = UObject.prototype.GetObjectClass;

**Comment by mflux** [comment]
I've tried running HelloBlueprint example and that one is failing as well it seems.

![screenshot 2016-03-03 18 02 58](https://cloud.githubusercontent.com/assets/1041360/13515915/330be9fe-e16a-11e5-976e-99aef231a081.png)

**Comment by mflux** [comment]
Alright I was able to get it working again by reverting to the old unrealEngineClassId global method you had in an earlier uclass.js.

    module.exports = function () {
        global.nextUnrealEngineClassId = global.nextUnrealEngineClassId || 0
        function fetchClassId() {
            return global.nextUnrealEngineClassId++
        }

And then...

            // get a classname
            let className = `${orgClassName}_C${fetchClassId()}`;

Instead of using the for loop and then testing UObject.Find, since that is unavailable through aliases. Hopefully we can get a correct fix for this at some point :)

**Comment by nakosung** [comment]
Actually `UObject.Find` is exposed via `JavascriptIsolate_Private.cpp`. It isn't a javascript function, so it cannot be available if you have a right build.
