### ISSUE TITLE
Node modules

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#27]
I installed Math.js from http://mathjs.org/ in Content/Scripts however when I loaded my project into Unreal, Unreal detected the new files and mistakenly thought I was trying to import a data table, see:

https://www.dropbox.com/s/iwhdw1vxtag9g73/Screenshot%202016-02-11%2002.46.23.png?dl=0&preview=Screenshot+2016-02-11+02.46.23.png

Apart from that, trying to use the library like so:

```javascript
let math = require('mathjs')
console.log(math.sqrt(4))
```

Resulted in an "Invalid script for require" error in the console, see:

https://www.dropbox.com/s/czojbpbn1furxse/Screenshot%202016-02-11%2002.48.47.png?dl=0&preview=Screenshot+2016-02-11+02.48.47.png

I also tried installing the Node module in Plugins/UnrealJS/Content/Scripts with no success.

Is there a special way/place to install/require modules that aren't included with Unreal.js by default?

**Comment by nakosung** [comment]
1. Regarding your first question, please refer to https://github.com/ncsoft/Unreal.js/wiki/Annoying-automatic-reimport-for-package.json.

2. The problematic script(fraction.js) directly writes to exports instead of module.exports. I'll add support for this kind of usage.

**Comment by nakosung** [comment]
Please check out 19e6636aa.

**Comment by Youdaman** [comment]
Thanks! I'll wait til the next build is available as I just saw the V8 stuff is a 1.1GB download :)

**Comment by Youdaman** [comment]
I downloaded V8 anyway, and put it in Unreal.js\Plugins\UnrealJS, but does there need to also be a .sln  or .uproject file there in order to build a new version of the plugin? Apologies if this is a noob question.

**Comment by Youdaman** [comment]
Nevermind, I think I found my answers: https://wiki.unrealengine.com/An_Introduction_to_UE4_Plugins

**Comment by Youdaman** [comment]
Actually no, I'm stuck. I think I need a .sln file from you :)

**Comment by nakosung** [comment]
There is 'Build project' for building unreal.js plugin. :) You can generate .sln from build.uproject.

**Comment by Youdaman** [comment]
Thank you. I did that, opened it in Visual Studio, built it, it succeeded, but I don't see where it creates the new version of the plugin -- do I need to change something in its settings? I can see red icons which indicated that these targets are being ignored (and so probably not being built at all) see:

https://www.dropbox.com/s/bvruvcb0240pbvv/Screenshot%202016-02-12%2012.13.04.png?dl=0

Also I tried running the build.bat from cmd but no luck, see:

https://www.dropbox.com/s/wtptsix6exqxmty/Screenshot%202016-02-12%2012.12.05.png?dl=0

Apologies if there's a step I'm missing.

**Comment by nakosung** [comment]
New binaries should be found in `unreal.js/Plugins/UnrealJS/Binaries`. Please make sure your binary's timestamp updated.

**Comment by Youdaman** [comment]
Excellent! You are a gentleman and a scholar :)

**Comment by nakosung** [comment]
Okay, everything seems fine. Happy js-ing!
