### ISSUE TITLE
In both tested versions, 4.22 and 4.24, "setTimeout is not a defined function"

### ISSUE THREAD

**Issue by NoEndParens** [ncsoft/Unreal.js#271]
Hey, I'm just trying to run one of the examples and it's giving me an error that setTimeout, a function that exists natively in Javascript, isn't a function.

Anyone know why I'd be getting that?

Thanks in advance.

**Comment by NoEndParens** [comment]
I think for people beginning with this plugin, things like "bootstrap.js" being separated from the marketplace version seem very counter-intuitive. This plugin seems pretty nice though even with the severe lack of documentation. I like it better than the Unreal python implementation, which had a similar problem, and I've already shipped a game on Steam using that. 

Thank you for maintaining it regardless.

**Comment by Peege151** [comment]
Did you ever figure out why you were getting that issue?  I am too and I feel like I shouldn't be.  I shall investigate bootstrap.js

**Comment by Peege151** [comment]
Yeah, just coming back here in case someone else stumbles across this issue they won't have to go anywhere else.

I'm not exactly sure what's happening, like NoEnds was saying, the build isn't exactly complete without some polyfills etc?

This solves the problem though

`Context.WriteAliases(Context.Paths[0] + 'aliases.js')
Context.RunFile('aliases.js')
Context.RunFile('polyfill/unrealengine.js')
Context.RunFile('polyfill/timers.js')`

I have the script in the same directory as aliases.js
