### ISSUE TITLE
iOS support? Planned?

### ISSUE THREAD

**Issue by grisevg** [ncsoft/Unreal.js#28]
Sorry if it was already answered but I couldn't find it.

As far as I know Apple does not allow iOS apps to run custom V8 vms. Instead all apps must use Apple's JavascriptCore runtime. This is for example what react native does.

I couldn't see any references to JavascriptCore in Unreal.js, so I assume it won't work for iOS.

Do you plan to add support for it in the future?

**Comment by nakosung** [comment]
For now I have no plan for supporting other platforms which don't allow V8. But unreal.js is an open-source project, I'm expecting some nice pull request which enables switching over multiple javascript engines.
