### ISSUE TITLE
Passing TArrays from Ue4 blueprints to java script.

### ISSUE THREAD

**Issue by minnakan** [ncsoft/Unreal.js#315]
Hi, I have a blueprint actor that is subclassed in javascript(from helloBlueprint.js example). I have then overridden a blueprint function to simply log the parameter that is passed to it. This works fine for strings, integers and floats. However when I pass a TArray of bytes and log its length, the output is zero. The arrays length in blueprints after calling the overridden function is also zero(passing by ref?). 
How would I go about passing an array of bytes from Ue4 blueprints or cpp to a java script function?
Thank you. Any help is much appreciated.

**Comment by getnamo** [comment]
There's https://github.com/ncsoft/Unreal.js/wiki/Huge-array-fast-access and https://github.com/ncsoft/Unreal.js/wiki/Huge-typed-array
