### ISSUE TITLE
UE5 Support

### ISSUE THREAD

**Issue by drfbwilliams** [ncsoft/Unreal.js#316]
Hi there,

Are there any plans to compile an update for this awesome project to run on UE5?

Many thanks

**Comment by kramsurfer** [comment]
Same question.  thanks!

**Comment by KaSakee** [comment]
Same here

**Comment by getnamo** [comment]
related: https://github.com/ncsoft/Unreal.js/issues/296

**Comment by crocuis** [comment]
Fixed. https://github.com/ncsoft/Unreal.js-core/commit/be215c85004e064c651ecd1931c97c5ba31872ab

**Comment by drfbwilliams** [comment]
@crocuis - thanks a ton
