### ISSUE TITLE
Issues while opening JavascriptPlayground project

### ISSUE THREAD

**Issue by c1tr00z** [ncsoft/Unreal.js#32]
When i try to open JavascriptPlayground.uproject after i did what install&play instruction tells me, i get these error messages in JavascriptConsole:
`LogLinker: Warning: The file 'D:/dev/apps/Unreal.js/Examples/Content/Color.uasset' contains unrecognizable data, check that it is of the expected type.
LogLinker: Warning: The file 'D:/dev/apps/Unreal.js/Examples/Content/Color.uasset' contains unrecognizable data, check that it is of the expected type.
LogUObjectGlobals: Warning: Failed to find object 'Material /Game/Color.Color'
Error: d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\instantiator.js:170: TypeError: Cannot read property 'GetEditorWorld' of undefined
Error: TypeError: Cannot read property 'GetEditorWorld' of undefined
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\instantiator.js:170:48
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\instantiator.js:408:3
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\instantiator.js:410:25
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:7:24
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:674:3
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:676:25
Error:     at d:\dev\apps\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:9:12
Error:     at d:\dev\apps\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:117:3
Error:     at d:\dev\apps\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:118:25
Error:     at spawn (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\editor.js:28:12)
< Invalid script for require
Error: d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:8: TypeError: Cannot read property 'conv' of undefined
Error: TypeError: Cannot read property 'conv' of undefined
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:8:28
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:674:3
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\UMG.js:676:25
Error:     at d:\dev\apps\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:9:12
Error:     at d:\dev\apps\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:117:3
Error:     at d:\dev\apps\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:118:25
Error:     at spawn (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\editor.js:28:12)
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\editor.js:39:40
Error:     at Array.map (native)
Error:     at main (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\editor.js:39:26)
< Invalid script for require
Error: d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:115: TypeError: Cannot read property 'text' of undefined
Error: TypeError: Cannot read property 'text' of undefined
Error:     at tag (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:115:20)
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:132:28
Error:     at Array.map (native)
Error:     at block (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:130:40)
Error:     at tag (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:109:28)
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:132:28
Error:     at Array.map (native)
Error:     at block (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:130:40)
Error:     at tag (d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:109:28)
Error:     at d:\dev\apps\Unreal.js\Examples\Plugins\UnrealJS\Content\Scripts\jade-umg.js:132:28
< Invalid script for require
Error: TypeError: require(...) is not a function`

And no one assets not visible in UE Editor. What i did wrong?

**Comment by nakosung** [comment]
Assets was uploaded via `git-lfs`. Please refer to `README.md` and follow instructions to install `git-lfs`.
