### ISSUE TITLE
how to user GWorld.GetActorOfClass()

### ISSUE THREAD

**Issue by ladyishenlong** [ncsoft/Unreal.js#325]
how to use GWorld.GetActorOfClass()  Call methods in other blueprints I didn't find the documentation

**Comment by mhale1** [comment]
Something like this works fine for me in development/editor mode:
```
const MyBlueprintUC = Blueprint.Load("/Game/MyBlueprint").GeneratedClass;
console.log(GWorld.GetActorOfClass(MyBlueprintUC).MyProperty);
```

**Comment by ladyishenlong** [comment]
> Something like this works fine for me in development/editor mode:
> 
> ```
> const MyBlueprintUC = Blueprint.Load("/Game/MyBlueprint").GeneratedClass;
> console.log(GWorld.GetActorOfClass(MyBlueprintUC).MyProperty);
> ```

const MyUC= Blueprint.Load("/Game/test2").GeneratedClass;
console.log("---------------------------------")
console.log(GWorld.GetActorOfClass(MyUC).getName)

![84A9D55EFCA1103C27A3F0B362400A68](https://user-images.githubusercontent.com/30828481/182288137-c15763a5-421b-4529-8f6f-48329e96bb33.png)

![9D13EB85B0D96BE01A5F9D3F9AD8FDAB](https://user-images.githubusercontent.com/30828481/182288167-8595af07-67be-48d1-8b25-608c7be47084.png)

LogWorld: Bringing World /Game/UEDPIE_0_NewMap.NewMap up for play (max tick rate 0) at 2022.08.02-11.50.53
Javascript: ---------------------------------
Javascript: function getName2() { [native code] }

Thanks for your reply, I tried it
I can see the log but the method is not executed

**Comment by ladyishenlong** [comment]
> Something like this works fine for me in development/editor mode:
> 
> ```
> const MyBlueprintUC = Blueprint.Load("/Game/MyBlueprint").GeneratedClass;
> console.log(GWorld.GetActorOfClass(MyBlueprintUC).MyProperty);
> ```

ok I know what happened 

const MyUC= Blueprint.Load("/Game/test2").GeneratedClass;
console.log("---------------------------------")
console.log(GWorld.GetActorOfClass(MyUC).getName2())

this is right
