### ISSUE TITLE
4.11?

### ISSUE THREAD

**Issue by timbur** [ncsoft/Unreal.js#36]
What would it take to get this working with 4.11?  I think I may just need the binaries.

**Comment by nakosung** [comment]
I haven't tried with 'preview' version, but I think that there would be no roughness to get it working.

**Comment by timbur** [comment]
I'm confused about these steps in the Build section of the README:
* `mklink /d /j Build/Plugins Plugins`
* `mklink /d /j Examples/Plugins Plugins`

**Comment by timbur** [comment]
BTW I'm actually trying to use this as a plugin within https://github.com/EpicGames/UnrealTournament/tree/1f48d730850bfc8f2245e4939991a0440a110655/UnrealTournament.

**Comment by timbur** [comment]
I think I've almost got it.  There are a couple of minor errors that need to be fixed for the upgrade to 4.11.  My C++ is a bit rusty but I think I can fix them.

**Comment by nakosung** [comment]
Pure blueprint uproject doesn't generate a Visual studio solution file which is required to build Unreal.js as a game plug-in. (Of course you can build Unreal.js as an engine plugin) So a blank c++ project is needed to build and built binaries are shared with pure blueprint uproject's via symbolic links.

**Comment by timbur** [comment]
The UT4 source includes GenerateProjectFiles.bat.

I'm only running into one problem now.  In JavaScriptEditorGlobalDelegates, the call to `OnFileLoadProgressUpdated` has changed for 4.11.  It now accepts an `IAssetRegistry::FFileLoadProgressUpdateData` as an argument, so it should look like this:
```
void OnFileLoadProgressUpdated(const IAssetRegistry::FFileLoadProgressUpdateData& ProgressUpdateData);
```

I can't seem to get it to include `IAssetRegistry` as a dependency though.  :(  My C++ is rusty and all of this seems like a bunch of convoluted magic to me right now lol.

Other than that, if I just comment it out, I can compile the plugin now after a few other errors were fixed.  I'll submit a pull request for your reference in the future if/when you update to 4.11.

**Comment by nakosung** [comment]
As I mentioned in your PR, I'll test and merge PR after official 4.11 build. :)

**Comment by timbur** [comment]
@nakosung can you help me with something when you get a chance?

If you look at https://github.com/ncsoft/Unreal.js/blob/f436b70034dc984c078bbec4fb667a37702c816c/Plugins/UnrealJS/Source/JavascriptEditor/JavascriptEditorGlobalDelegates.h#L250, in 4.11, I get an error which I think means this actually needs to be:
```cpp
void OnFileLoadProgressUpdated(const IAssetRegistry::FFileLoadProgressUpdateData& ProgressUpdateData);
```

But I always get an error saying `IAssetRegistry` is undefined.  I've tried adding the AssetRegistry to `JavascriptEditor.Build.cs` and `#include "IAssetRegistry,h"` but nothing seems to work.

**Comment by nakosung** [comment]
We are updating unreal.vs! Please be tuned. :) It would be great if you could comment out erroneous lines.

**Comment by nakosung** [comment]
Current master branch is compatible with current latest 4.11. :)

**Comment by timbur** [comment]
Nice!  Thanks, I'll try it out when I get a chance.

**Comment by nakosung** [comment]
Prebuilt binaries for 4.11 has been uploaded! :)
