### ISSUE TITLE
How editor extension work?

### ISSUE THREAD

**Issue by damody** [ncsoft/Unreal.js#37]
I want to run [extension-spiralGenerator.js](https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/extension-spiralGenerator.js)
but I have no idea about show the page like 
![](https://github.com/ncsoft/Unreal.js/blob/master/doc/images/UnrealJs_editor.gif)
https://github.com/ncsoft/Unreal.js/blob/master/doc/images/UnrealJs_editor.gif
Could you explain how to execute?

**Comment by nakosung** [comment]
Actually there is a bug which prevents extensions to be available by default. If you want to see it working, open your favorite editor and modify extension-spiralGenerator.js slightly and save it. Editor will recognize modification and reload it.

**Comment by nakosung** [comment]
I updated `extension-spiralGenerator.js`. Please check it out. :)
