### ISSUE TITLE
Extending blueprint functions + arguments will crash UE4

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#39]
To reproduce:

1. Open HelloBlueprint
2. Open ExampleBlueprint
3. Give CustomEvent a new Input (any type) like so:

![screenshot 2016-03-03 18 30 43](https://cloud.githubusercontent.com/assets/1041360/13516333/1783d526-e16e-11e5-8c6a-2afb520ad115.png)

4. Run the game
5. UE4 crashes

This happens whenever you give a function you're overriding an argument.

        // Override an event which was declared in Blueprint
        CustomEvent() {
            console.log("This is javascript")
        }

Actually giving it an argument in JS

        // with or without signature
        CustomEvent(newParam/*string*/) { 
            console.log("This is javascript")
        }

Will still result in a crash.

Because of this, events such as key presses, button clicks from UMG, etc cannot pass in relevant data to JS.

**Comment by nakosung** [comment]
Hmm.. I had tried to reproduce the problem but I failed. btw, regarding `UObject.Find` it seems working fine for me. I think it is possible that your unreal.js installation is stale or corrupt.

**Comment by mflux** [comment]
Okay I will try a full reinstall and report back.

**Comment by mflux** [comment]
Hi Nako, here are the steps I've done to reproduce the UObject.Find issue from a fresh install of Unreal.js. The install instructions were always a bit unclear, so maybe I did something wrong which you can see. If I can fix this issue then maybe this will help us write better install instructions :D 

Alright so..

Deleting old UnrealJS folder from plugins
![screenshot 2016-03-05 13 55 03](https://cloud.githubusercontent.com/assets/1041360/13550839/bc006ab0-e2db-11e5-870a-2e38bdba0450.png)

Downloaded a fresh copy from https://github.com/ncsoft/Unreal.js/releases/download/prebuilt-win64-20160305/UnrealJS.Prebuilt.4.10.4-20160305-1.zip
![screenshot 2016-03-05 13 59 16](https://cloud.githubusercontent.com/assets/1041360/13550842/d0a04c2e-e2db-11e5-8760-e0874d8c1f46.png)

Copied the folder directly into the Plugins folder of /Engine/
![screenshot 2016-03-05 13 59 51](https://cloud.githubusercontent.com/assets/1041360/13550847/f867aaea-e2db-11e5-98e5-98aafc54d020.png)

The instructions were unclear here. On github it tells you to unzip unto Examples/Plugins/UnrealJS. There is no Examples folder by default in my 4.10/Engine folder anywhere. There is a Plugins folder only.

In addition, the Prebuilt zip doesn't include an Examples directory. The github repo does though.
![screenshot 2016-03-05 14 02 08](https://cloud.githubusercontent.com/assets/1041360/13550849/12a47730-e2dc-11e5-82b6-a0f66daa3477.png)

I download the repo as a zip from github.
![screenshot 2016-03-05 14 03 25](https://cloud.githubusercontent.com/assets/1041360/13550864/5617ee84-e2dc-11e5-87e1-8b401c372e61.png)

I copied the Examples folder from this zip file, into /Engine/
![screenshot 2016-03-05 14 05 00](https://cloud.githubusercontent.com/assets/1041360/13550869/684e7776-e2dc-11e5-9d9d-f5c52f3ec355.png)

NPM installs correctly
![screenshot 2016-03-05 14 06 21](https://cloud.githubusercontent.com/assets/1041360/13550872/7d57c474-e2dc-11e5-9919-c301a9cdd36c.png)

Launching UE4
![screenshot 2016-03-05 14 06 33](https://cloud.githubusercontent.com/assets/1041360/13550877/8cd02e6e-e2dc-11e5-83cd-dec1e82682f0.png)

Opening the JavascriptPlayground uproject
![screenshot 2016-03-05 14 06 57](https://cloud.githubusercontent.com/assets/1041360/13550880/9943ac34-e2dc-11e5-879c-4e5c75b62a20.png)

Opened HelloBlueprint map and hit play, you can see UObject.Find is not found.
![screenshot 2016-03-05 14 07 19](https://cloud.githubusercontent.com/assets/1041360/13550888/bbdd0808-e2dc-11e5-8318-aac625d3790c.png)

Anything you see I'm doing incorrectly? The only part that was very unclear was the Examples folder and that was missing from the Prebuilt, as instructed to download.

**Comment by mflux** [comment]
Alright I figured it out :+1: 

There were UnrealJS binaries sitting inside 4.10/Engine/Binaries/Win64.

I put them there when I was installing UnrealJS for the first time because it was complaining about binaries missing. I guess these were stale and conflicting with the Plugin binaries. All other things seem to work!

**Comment by nakosung** [comment]
It's great to see your build is working. Actually my instruction seem to be incomplete, I had setup my directory layout with symlinks (`mklink`). 

PR for installation instruction would be great. :)
