### ISSUE TITLE
ScriptGeneratorPlugin, ScriptPlugin, and/or ScriptEditorPlugin?

### ISSUE THREAD

**Issue by timbur** [ncsoft/Unreal.js#40]
It doesn't look like Unreal.js uses any of these.  Is that true?  If so, why not?

Here's a thread about it: https://forums.unrealengine.com/showthread.php?3958-Scripting-Language-extensions-via-plugins

**Comment by nakosung** [comment]
It doesn't give enough flexibility and performance to script languages. It generates cpp stub code from script land. Instead of being a polite guest in UE4, Unreal.js lets you can control and access almost every features UE4 offers like a master of UE4. :)

**Comment by timbur** [comment]
Ah ok, awesome!  Thanks for the clarification.  I'll probably be submitting more PRs and maybe some wiki updates as well soon.

**Comment by nakosung** [comment]
Thank you! :)

2016-03-12 5:01 GMT+09:00 Tim Burgess <notifications@github.com>:
