### ISSUE TITLE
OnlineSubsystem via Unreal.js

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#42]
I followed the guide by Michael Allar on enabling Steam integration here: http://allarsblog.com/2016/02/26/BasicSteamIntegration/

And I now have a steam overlay in my game:
![screenshot 2016-03-13 12 33 59](https://cloud.githubusercontent.com/assets/287330/13726385/434084fe-e919-11e5-8c5d-d3a044edfbea.png)

I would like to access the OnlineSubsystem from JS however it complains this doesn't exist.

So my guess is I have to follow the instructions from Allar's article under the section "Linking The OnlineSubsystemSteam Module" -- but then the Steam overlay works so this might be unnecessary.

Or maybe it's just that it's not possible to access OnlineSubsystem using Unreal.js yet?

Any clues would be appreciated :)

**Comment by nakosung** [comment]
I have no experience with OnlineSession subsystem, but it seems you can access `GWorld.GetGameInstance().OnlineSession` to get a session object. :)
