### ISSUE TITLE
helloJade and helloUMG work in standalone but helloScope does not

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#43]
I can see the UMG widgets for the helloScope example using PIE (play in editor) but when I launch that example using "Standalone Game" nothing appears. What's the difference between it and the other Jade/UMG examples? I'm guessing it's the devjade or devrequire scripts doing stuff only in the editor?

**Comment by nakosung** [comment]
Probably devrequire, devjade is not working well outside editor, btw monitoring feature is only being supported within editor. 

FYI, I'll mark jade things including scope as deprecated soon. We have decided not to use it anymore and to use plain 'UMG' with a new binding system which uses Object.observe. (For better performance)

**Comment by Youdaman** [comment]
No worries, sounds good re plain UMG with new binding system.

As for this problem (in case anyone else has the same issue) I believe it's because in the helloScope example there is a line: `let ES = JavascriptEditorStyle;`

However in https://github.com/ncsoft/Unreal.js/blob/master/Plugins/UnrealJS/Source/JavascriptEditor/JavascriptEditorStyle.h there is a `#if WITH_EDITOR` block.

So the button style probably only loads when you're using the editor and not in standalone because of this.

**Comment by nakosung** [comment]
Ah, yes. It just borrows bunch of styles from editor. So without editor linked properly, it cannot get valid style objects.

**Comment by Youdaman** [comment]
I'm interested in hearing more about the new binding system which uses Object.observe

Where I'm at is I have a list of Steam friends and I'm wanting to show them on the screen -- currently I'm using BLUI https://github.com/AaronShea/BLUI to render them to an AngularJS page, but the problem is the avatar provided by the session plugin I'm using is in the form of an Unreal Texture and not an image URL and so I think I'll have to use UMG after all.

So I'd love to know the best way to send data to/from UMG via Unreal.js (that won't be deprecated) :)

Is the helloUMG example the best one to copy from?

Also, if I'm using a plugin for the session and Steam friends that works in Blueprint, what is the best way to pass that data to Unreal.js or be able to call its functions from Unreal.js so that I can then build my HUD using UMG in JS? Any pointers to the existing examples or docs welcome (especially stuff that's not going to be deprecated).

**Comment by nakosung** [comment]
Pseudo-code seems like below;

```
function image(url) {
  let brush = new SlateBrush
  brush.Texture = url // I'm not quite sure about this for now. :(
  return UMG(UImage,{Brush:brush})
}
let design = 
UMG.div({},
  logic.players.map(player => 
    UMG.span({},
      image(player.avatarUrl),
      UMG.text({},player.name)
    )
  )
)
```

`logic.players.map` is just like `ng-repeat`, but it doesn't handle dynamic binding. So it just does only what jade `each` does. With new binding, dynamic binding can be coded like below.

```
UMG.div({},
  binding.map(logic,players, player =>
    UMG.span({},
      image(player.avatarUrl), // which is static per user-basis
      UMG.text({},player.name), // which is also static
      binding.tick({Text:_ => player.positionString}, 
        UMG.text({},'')
      ), // which may be updated everyframe
      binding.wrap({Text:_ => player.hp},
        UMG.text({},'hp here')
      ) // which may be updated occasionally
  )
)
```

:)

**Comment by Youdaman** [comment]
No worries re Steam/session, it's just a list of key/value pairs that I'm passing, similar to your example with player.name and player.avatarUrl etc. :)

With UMG stuff like UMG.text({}, foo) where do I figure out what goes in the {}? I was thinking it was the C++ API docs but maybe I just need to play with the UMG Designer and see what params the various types of components/fields take?

Anyway, looking forward to an example in the repo (and build release) of what you've described, especially the interactive stuff :)

**Comment by nakosung** [comment]
Yes. It is just a bunch of UMG parameters with some helpers.

```
{ Slot : { SizeRule : 'Fill' } } == { 'slot.size-rule' : 'Fill' }
{ Font : { Size : 20 } } == { 'font.size' : 20 }
```

Binding stuffs will be updated after I return back from GDC. :)

**Comment by Youdaman** [comment]
Have fun at GDC :)

In the meantime I'm making some progress with a variation of your pseudocode:

`
function avatar(friend) {
  let brush = PC.GetSteamAvatar(friend).avatar
  return UMG(UImage,{Brush:brush})
}
...
_.map(friends,(friend) =>
  UMG.span({},
    avatar(friend),
    UMG.text({},friend.DisplayName)
  )
)
`

Where GetSteamAvatar is a BP function I've created that calls the BP function provided by the Steam plugin I'm using to fetch the avatar (which comes back as a 2D Texture and I then convert to a Brush in BP before returning).

I did try to call some of the BP functions (or at least their underlying C++ functions as I have the source) for the plugin but I came across a problem where they've implemented a struct that I don't know how to emulate in JS.

Anyway, making nice progress thanks to your suggestion, so thanks :)

![screenshot 2016-03-16 00 12 41](https://cloud.githubusercontent.com/assets/287330/13779682/5c4679f6-eb10-11e5-846a-be224bcb1b78.png)

**Comment by nakosung** [comment]
It's great to see your nice widgets on screen. You can create USTRUCT instance like below;

0. {X:1,Y:1,Z:1}                    - untyped. but safe to cast 
1. Vector({X:1,Y:1,Z:1})       - casted into FVector
2. let x = new Vector()         - create a new instance of FVector

:)

**Comment by Youdaman** [comment]
I forgot to remove the "F" from the struct name! I was trying `let netId = new FBPUniqueNetId()` which threw a reference error, whereas `let netId = new BPUniqueNetId()` works! Thanks again nakosung :)

**Comment by Youdaman** [comment]
I've worked out how to do things using only JS :)

```
            let avatarTexture = AdvancedFriendsLibrary.GetSteamFriendAvatar(PC, friend.UniqueNetId, SteamAvatarSize.SteamAvatar_Large)
            let avatarBrush = WidgetBlueprintLibrary.MakeBrushFromTexture(avatarTexture)
            return UMG(UImage,{Brush:avatarBrush})
```

So now I don't need to subclass from a BP PlayerController -- it's just a matter of working out what functions to call.

Anyway, I'll close this ticket, thanks again for all your help nakosung!
