### ISSUE TITLE
Using Unreal.js for an editor plugin?

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#44]
Unreal.js is awsome! That's why I would like to use it for a plugin based on an [EdMode](https://docs.unrealengine.com/latest/INT/API/Editor/UnrealEd/FEdMode/index.html) and an [ModeToolkit](https://docs.unrealengine.com/latest/INT/API/Editor/UnrealEd/Toolkits/FModeToolkit/index.html).

I can think of two ways of doing it:

- create the plugin in c++ (implementing the custom EdMode and ModeToolkit), create a project using this plugin and UnrealJS plugin, find a way to communicate between the c++ code and the javascript code,
- extend the c++ code of UnrealJS to be able to create an EdMode and a ModeToolkit in javascript, and create the entire plugin in javascript,

The first solution seems more simple. How can I communicate from c++ to javascript? I would need to call some javascript code from c++, and the other way around (call c++ code from javascript). 
(I would need to share objects among the two sides, but this should not be a problem)

**Comment by nakosung** [comment]
Currently extending editor with unreal.js is not full featured. So my recommendation would be your first solution. To communicate your c++ with js land, you can just let your logic exposed as UObject so that it can be accessed by blueprints. There is no need to write specific glue code for js.

**Comment by arthursw** [comment]
Thanks! Can you explain how to expose logic as UObject and access it via Blueprint?

**Comment by arthursw** [comment]
Here is my Bluprintable UClass:

```
UCLASS(BlueprintType, ClassGroup = Script, Blueprintable, hideCategories = (ComponentReplication), editinlinenew, meta = (BlueprintSpawnableComponent))
class UPB : public UObject
{
	GENERATED_UCLASS_BODY()
public:
	UFUNCTION(BlueprintNativeEvent, Category = "Javascript")
	void OnMouseMove(const FVector2D& Position);
};

// .cpp

void UPB::OnMouseMove_Implementation(const FVector2D& Position)
{
	UE_LOG(LogTemp, Warning, TEXT("On mouse move c++ implementation."));
}

```
I call the mouse move event in my custom EdMode:

```
bool FCustomEdMode::InputAxis(FEditorViewportClient *InViewportClient, FViewport *Viewport, int32 ControllerId, FKey Key, float Delta, float DeltaTime)
{
	if (Key == EKeys::MouseX || Key == EKeys::MouseY)
	{
		MouveMoveDelegate.ExecuteIfBound(FVector2D(Viewport->GetMouseX(), Viewport->GetMouseY()));
	}
	return false;
}

```

In my project, I have a custom blueprint (PB) which inherits from the Blueprintable class (UPB).
In my extension-EditorPlugin.js I create a subclass of this blueprint, and an instance of it:
```

class PB extends Blueprint.Load('/Game/PB').GeneratedClass {
        ctor() {}
        // Override an event which was declared in Blueprint
        OnMouseMove(Position) {
            console.log("On mouse move javascript: " + Position)
        }
    }
    const uclass = require('uclass')().bind(this,global)
    PB_C = uclass(PB)
    Root.pb = new PB_C()

```
It goes into the c++ function, but it never goes in the javascript OnMouseMove() function. 

(And more strange: as soon as I recompile my blueprint, the c++ event is not called anymore, even if the blueprint is totally empty and there is no instance of it).

**Comment by arthursw** [comment]
There is probably an easier way to communicate between C++ and JS (custom blueprint shouldn't be necessary?)...

**Comment by nakosung** [comment]
'FastCall' feature does the job you want. But I don't recommend, because I want Javascript invisible in C++ land. :)

**Comment by arthursw** [comment]
Thanks :+1: This should be good enough for me. Do you recommend the Blueprint method, as I did it? (I'm just curious)

**Comment by nakosung** [comment]
Yes. I recommend BP method because it gives loosely coupled codes. :)

**Comment by nakosung** [comment]
Closing this issue. :)
