### ISSUE TITLE
Path problem in V8.Build.cs

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#45]
I had to change

            PublicIncludePaths.Add(Path.Combine(ThirdPartyPath, "v8", "Includes"));

to

            PublicIncludePaths.Add(Path.Combine(ThirdPartyPath, "v8", "include"));

in V8.Build.cs to be able to compile. It works fine now!

**Comment by nakosung** [comment]
Could you make it as a PR? Thanks!

**Comment by arthursw** [comment]
Well, I would like to, but this code comes from the [Snippet editor release](https://github.com/ncsoft/Unreal.js/releases/tag/snippet-editor) (JavascriptSnippetEditorSample.zip), so I don't think I can do a Push Request : /

**Comment by whiteted** [comment]
When compiling I get the error:
"EXEC : error : Couldn't find module rules file for module 'V8'. "
Is this just a missing V8.Build.cs file because I'm missing some files? or something related to this path problem?

**Comment by mflux** [comment]
I ran into this issue. When compiling you need to download the V8 prebuild (the 1.6 gig zip)  https://github.com/ncsoft/Unreal.js/releases/tag/v8-msvc2015

And then place that into {YourGameOrEngineFolder}\Plugins folder so that...

{YourGameOrEngineFolder}\UnrealJS\ThirdParty\v8\lib gets created

The zip already has the full path from UnrealJS, hence you should unzip directly into the Plugins folder. It's pretty confusing.

Also, I could only get Unreal.js compiling with the /opt/ branch of UnrealJS https://github.com/ncsoft/Unreal.js/tree/opt

Master branch and Unreal.js-Core repo both had errors.

**Comment by whiteted** [comment]
I thought I might be missing that, but didn't know what to do with all 1.6 gigs of it!
I've just been working around it by removing the unrealJS folder from [myProject]/plugins (but leaving all scripts etc. in content) then coding,compiling,tweaking,compiling before replacing the plugin and running the actual project O:)

**Comment by nakosung** [comment]
Hmm... I've setup my dev env on computers successfully, so I think build instruction makes things confusing. ..

**Comment by wildermuthn** [comment]
I was hit by the "EXEC : error : Couldn't find module rules file for module 'V8'. " error for many hours. I needed to have both v8/lib (from the download link in the releases) and v8/include (its another repo inside this repo, which I never pulled down from https://github.com/ncsoft/Unreal.js-core). Once I had both those v8 directories, and I added an empty class to my project, master built successfully. 

To get everything working properly when the executable was run, however, I had to include the plugin content directory, but also had to include content/Scripts. Still working on getting the shipping executable running.

**Comment by aking** [comment]
I ran into the exact same problem: "EXEC : error : Couldn't find module rules file for module 'V8'."  I fixed it by just copying the 'Source' dir from ncsoft/Unreal.js-core into the Plugins/UnrealJS dir.  After that, I'm able to compile C++ code again.

**Comment by Grinkers** [comment]
The way I have it set up is:
I'm pulling with `git pull && git submodule update --init`
Also I have a mklink /d /j between Unreal.js\Plugins\UnrealJS and [project]\Plugins\UnrealJS

Doing this I've had no problems pulling updates from Unreal.js and have it automatically sync in my separate game project.

**Comment by nakosung** [comment]
Prebuilt binaries package is not a single-step-ready-to-go solution. I think I should publish 'fully functional standalone package' instead of current zip file which contains only binaries. :)
