### ISSUE TITLE
How do method params get converted to Unreal objects?

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#48]
The plugin I'm using has a function as follows:

`UTexture2D * UAdvancedFriendsLibrary::GetSteamFriendAvatar(APlayerController *PlayerController, const FBPUniqueNetId UniqueNetId, SteamAvatarSize AvatarSize)`

I'm able to successfully call this as:

`let texture = AdvancedFriendsLibrary.GetSteamFriendAvatar(PC, friend.UniqueNetId, SteamAvatarSize.SteamAvatar_Large)`

So I've worked out how to translate C++ into JS to do things like the above.

My question is how do method params get converted into Unreal/C++ objects, and more specifically, how can I cast JS objects to be their proper C++ type and have the same properties and methods?

What follows is a specific example.

I see later in that above function in C++ it has:

`uint64 id = *((uint64*)UniqueNetId.UniqueNetId->GetBytes());`

However my friend.UniqueNetId doesn't have a UniqueNetId property or GetBytes() method.

So I'm assuming that Unreal.js does some magic and converts the JS object I'm passing as a param to an instance of the appropriate class before handing it to C++ yes?

Is there a way that I can do this manually myself outside of that function if I want to get this same uint64 id? I've tried creating `new BPUniqueNetId()` variables in JS with no luck, but I reckon I'm not doing it correctly.

As far as I understand, this BPUniqueNetId is a variant of FUniqueNetIdString found here: https://docs.unrealengine.com/latest/INT/API/Runtime/OnlineSubsystem/FUniqueNetIdString/index.html
or maybe: https://docs.unrealengine.com/latest/INT/API/Runtime/OnlineSubsystem/FUniqueNetId/index.html

This is less a Steam-specific question and more a question of how do I correctly create objects using JS to match their C++ counterparts. There are some hints in your example demos such as `PlayerController.C(PC).bShowMouseCursor = true` and `PlayerController.C(PC).SetInputMode_GameAndUI(widget,false,false)` which I assume means "cast PC to be a PlayerController and set a property or call a method as that class" -- however I'm stuck with the example above regarding creating a proper UniqueNetId instance (and its property of the same name) that I can then call GetBytes() on.

**Comment by Youdaman** [comment]
Also, when I try texture.PlatformData I get nothing, so I'm guessing I need to instantiate texture as a proper UTexture via that .C() technique?

**Comment by nakosung** [comment]
The magic is 'keeping proper reference to USTRUCT instance' which is returned by past UE functions. I'm not familiar with advanced friends library, but I assume that it returns list of friends and receives 'handles' of friends which it returned previously. So Unreal.js keeps 'C++ instances' which was returned by that library and then passes them back to the library. :)

So you cannot create a new handle by `new Handle` in js, handle should be retrieved from UE functions.

**Comment by Youdaman** [comment]
> Regarding texture.PlatformData, it seems not to be exposed into BP world.

So is this to say that only things exposed by BP are available to Unreal.js?

**Comment by nakosung** [comment]
Yes. UnrealEngine doesn't know existence of private C++ data. If it is needed, one should mark as UPROPERTY or implement proper access UFUNCTION's.

**Comment by Youdaman** [comment]
That makes sense :)

On that note, given that PrintString is available to BP, why doesn't `KismetSystemLibrary.PrintString(GWorld, 'test')` work? Or am I supposed to access PrintString via another object/path?

**Comment by Youdaman** [comment]
I see that I can call `KismetSystemLibrary.PrintWarning('test')` and that shows up in the Output Log tab.

**Comment by Youdaman** [comment]
Oh nevermind I just realised the above prints to the screen when I launch standalone (which I need to in order for Steam to work) :)

**Comment by Youdaman** [comment]
Thanks for your help again nakosung!
