### ISSUE TITLE
Adding Components

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#50]
I have the following Character subclass:

```
  class MyCharacter extends Blueprint.Load('/Game/ThirdPersonCPP/Blueprints/ThirdPersonCharacter').GeneratedClass {
    ctor() {
      this.CollectionSphere = SphereComponent.CreateDefaultSubobject("CollectionSphere")
      this.CollectionSphere.SetSphereRadius(200)
      this.CollectionSphere.AttachParent = this.RootComponent
    }
    properties() {
      this.CollectionSphere/*VisibleAnywhere+Category:Javascript+CollectionSphere*/;
    }
  }

  let MyCharacter_C = require('uclass')()(global,MyCharacter)
  GWorld.GetGameMode().DefaultPawnClass = MyCharacter_C
```

This works fine in that I get the correct character running around, however the CollectionSphere doesn't seem to work correctly:

`TypeError: this.CollectionSphere.SetSphereRadius is not a function`

This is because `this.CollectionSphere` turns out to be a string and not a Component object (when I check using typeof or in the console if I set `global.sphere = this.CollectionSphere` in the ctor).

Is there a step I'm missing here?

**Comment by getnamo** [comment]
might be related to: https://www.smashingmagazine.com/2014/01/understanding-javascript-function-prototype-bind/

**Comment by nakosung** [comment]
type of CollectionSphere seems to be 'SphereComponent' but it is set as 'CollectionSphere'.

`this.CollectionSphere/*VisibleAnywhere+SphereComponent*/;`

:)

**Comment by Youdaman** [comment]
Haha of course, one word solution :)

I'd actually thought about trying that -- "I'll try that next after I finish with this possible fix" -- and then forgot. Thanks again @nakosung sir!

I was unsure from the example:

`this.MyComponent/*VisibleAnywhere+Category:Javascript+MyComponent*/;`

Perhaps change the property name so it doesn't match the property class in this example I think :)
