### ISSUE TITLE
Recent commits prevent successful build of UnrealJS plugin

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#51]
It seems that the merge and rollback commits on the 22nd March have broken things -- or at least I could not build the plugin using the latest version of the source and the v8 libs.

I found an older version last used on the 21st in another project of mine and it builds fine.

Here's the other issue where I list the steps to reproduce this problem and then solved it: https://github.com/ncsoft/Unreal.js/issues/49#issuecomment-200967255

**Comment by nakosung** [comment]
Current master is not compatible with 4.10. I had created branch '4.10' which can be compatible with 4.10 release. :)
