### ISSUE TITLE
How to actually get 'fs'?

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#52]
Hey Nako

According to https://github.com/ncsoft/Unreal.js/wiki/Working-with-node.js-modules

"Only small amount of functions are provided including timer functions(setTimeout, clearTimeout, ...), process.nextTick and fs.readFileSync"

However upon trying this...

    Error: c:\Users\Flux\Documents\Unreal Projects\CPCS\Content\Scripts\game\gamecore.js:1344: ReferenceError: readFileSync is not defined
    Error: ReferenceError: readFileSync is not defined    

My code in question. This is transpiled by grunt-babel, not sure if that matters.

    var fs = require('fs');
    function load( filePath ){
      return fs.readFileSync( filePath, 'utf8').split(/\r?\n/);
    }

**Comment by mflux** [comment]
Nevermind. It works on the js executed by UnrealJS but not by transpiled JS from grunt-babel. Looks like I'll just pass in 'fs' directly and access it from there!

**Comment by nakosung** [comment]
:+1
