### ISSUE TITLE
Missing declaration of "UClass" and "GWorld"

### ISSUE THREAD

**Issue by ConquestArrow** [ncsoft/Unreal.js#54]
I tried to use Unreal.js with TypeScript, then some declaration missing error occurred.

 * UnrealJS.Prebuilt.4.11.0-20160401-1.zip
 * TypeScript 1.8.7

Is that like a following definition not necessary?
```ts
declare class UClass{}
declare var GWorld:World;
```

**Comment by nakosung** [comment]
Currently *.d.ts is generated within editor environment which has no GWorld. As a remedy for this problem, you can manually regenerate *.d.ts within game environment by calling `Context.WriteDTS(Context.Paths[0] + 'typings/ue.d.ts')`.

**Comment by Youdaman** [comment]
Might be an idea to add `Context.WriteDTS(Context.Paths[0] + 'typings/ue.d.ts')` to https://github.com/ncsoft/Unreal.js/wiki/Autocompletion
