### ISSUE TITLE
Submodule not fetching

### ISSUE THREAD

**Issue by Grinkers** [ncsoft/Unreal.js#58]
I've never used git submodules before, so I might be doing something silly. Is "git submodule update" the correct way to pull from the core? When I try to pull or submodule update it fails. I think Unreal.js-core might be missing a push? 

Thanks for your time.

```
git submodule update
error: no such remote ref bf353ebe2b72f5f5edda3232aed7323a92b618a7
Fetched in submodule path 'Plugins/UnrealJS', but it did not contain bf353ebe2b72f5f5edda3232aed7323a92b618a7. Direct fetching of that commit failed.
```

**Comment by nakosung** [comment]
how about trying,
`git submodule update --init`

**Comment by Grinkers** [comment]
Works great, thanks!
