### ISSUE TITLE
Doesn't work in html5

### ISSUE THREAD

**Issue by axvm** [ncsoft/Unreal.js#59]
Hey,

I enabled `Unreal.js` plugin and packed my project in html5 platform. Compilation has been finished fine but in runtime i got this error:

>Plugin 'UnrealJS' failed to load because module 'JavascriptUMG' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.

In log i found more errors:
>[2016.04.10-22.09.06:755][ 0]LogInit: Selected Device Profile: [HTML5]
>[2016.04.10-22.09.07:138][ 0]LogModuleManager:Warning: ModuleManager: Module 'JavascriptUMG' not found - its StaticallyLinkedModuleInitializers function is null.
>[2016.04.10-22.09.07:138][ 0]LogModuleManager:Warning: ModuleManager: Module 'JavascriptHttp' not found - its StaticallyLinkedModuleInitializers function is null.
>[2016.04.10-22.09.07:139][ 0]LogModuleManager:Warning: ModuleManager: Module 'JavascriptWebSocket' not found - its StaticallyLinkedModuleInitializers function is null.

**Comment by Grinkers** [comment]
I don't believe HTML5 can be supported. It's probably not possible because the plugin requires V8 to be compiled. At the moment there's only Windows and Android (Linux and OSX should theoretically be not too hard). 
https://developers.google.com/v8/build

**Comment by nakosung** [comment]
Maybe there's someway to support HTML5 without V8... :8ball:

**Comment by axvm** [comment]
I heard the stories that some software has built-in v8 engine. :no_mouth:

**Comment by nakosung** [comment]
So HTML5 is not a supported platform for now. *sad*

**Comment by tamdrib** [comment]
Is there a chance of unreal.js being developed further to make this happen? HTML5 seems like the perfect place for unreal.js to be used, considering that JS is the ideal language for web development.

A project I am working on currently is trying to find ways to make calls to Google Speech through UE4, and I can't find a plugin or workaround to get access.

**Comment by axvm** [comment]
HTML5 still experimental so im not sure if it's possible... But it would be really great if we will have ability to develop software with js in ue for html5 platform.
