### ISSUE TITLE
How to use the ReplicatedUsing UPROPERTY

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#60]
I'm getting the following warning in the console:

`LogRep: Warning: FRepLayout::CallRepNotifies: Can't find RepNotify function OnRepHealth for property health on object MyCharacter_C1_5.`

Here's the associated code:

```
class MyCharacter extends Blueprint.Load('/Game/ThirdPersonBP/Blueprints/ThirdPersonCharacter').GeneratedClass {
    prector() {
      MyCMC_C.SetDefaultSubobjectClass("CharMoveComp")
    }
    ReceiveTick(DeltaTime) {
      this.health++
      this.TextRender.SetText(this.GetName() + "\n" + this.Role + "\n" + this.GetMovementComponent().Mass)
    }
    OnRepHealth(h) {
      console.log('health replicated', this.health)
    }
    properties() {
      this.health/*EditAnywhere+ReplicatedUsing:OnRepHealth+int*/;
    }
  }
```

I followed the example here: https://github.com/ncsoft/Unreal.js/wiki/UPROPERTY

I tried `OnRepHealth()` (without the h param) and it still gave the warning. Am I not declaring the function correctly?

**Comment by nakosung** [comment]
It requires proper function decorator to be parsed as a exported function.

**Comment by nakosung** [comment]
In case of overriding existing functions, unrealjs doesn't require function signature decorator.

**Comment by Youdaman** [comment]
Does this mean I need to have something like `OnRepHealth()/*something-goes-here*/` -- what is the "something-goes-here"? Or is the function supposed to be defined outside the class?

Sorry I don't understand, can you please give me an example or expand the example on the wiki page of a function that would use its health property? https://github.com/ncsoft/Unreal.js/wiki/UPROPERTY

**Comment by Youdaman** [comment]
I'm guessing the "something-goes-here" is either /*Server*/ or /*NetMulticast*/ right?

**Comment by nakosung** [comment]
Have you tried /*Any*/? It seems working. :)

```js
OnRepHealth() /*Any*/ {
}
```

**Comment by ArtyMcLabin** [comment]
Can somebody explain what are these decorators anyway and when can i find more information about these?
