### ISSUE TITLE
Input Binding example broken

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#62]
`helloInputBinding.js:38: TypeError: Cannot set property 'PlayerControllerClass' of undefined`

I'm guessing line 38 should read:

`Root.GetOuter().PlayerControllerClass = MyPC_C`

**Comment by nakosung** [comment]
Did you test in multiplayer configuration?

**Comment by nakosung** [comment]
It turns out just fine with current release.
