### ISSUE TITLE
Do u have a MAC version for  prebuilt UnrealJS plugin ?

### ISSUE THREAD

**Issue by jinkeep** [ncsoft/Unreal.js#65]

**Comment by se-panfilov** [comment]
Same question.

Please provide mac os version, or just provide some instruction how we can build it manually.

Many thanks

**Comment by nakosung** [comment]
To build Mac version you should build v8 for mac first, and add mac libraries (https://github.com/ncsoft/Unreal.js-core/blob/master/Source/V8/V8.Build.cs)

And add mac on whitelist platform(https://github.com/ncsoft/Unreal.js-core/blob/master/UnrealJS.uplugin)

:)

**Comment by jinkeep** [comment]
Could u build one and upload ? Thanks!

**Comment by HongPong** [comment]
I suspect the architecture issues are tricky enough it would be unwise to distribute built versions. 

If you have homebrew this will get you a v8 : `brew install v8` . I just got v8-5.0.71.33 quite easily.

**Comment by nakosung** [comment]
Okay, I will try to install UE4 and v8 on my mac book pro.

**Comment by nakosung** [comment]
![image](https://cloud.githubusercontent.com/assets/2463571/14941342/49215be8-0fd2-11e6-8979-ffc406efb74a.png)

Please stay tuned.

**Comment by nakosung** [comment]
FYI, mac version has some hack which causes memory leakage which only happens when you extend menu with javascript.

**Comment by EvelynY** [comment]
I install V8 and clone the MAC version to my project, I got this problem "Plugin missing or incompatible", how could I solve this?

**Comment by monokrome** [comment]
What are "the architecture issues" making this difficult to distribute a build for?

**Comment by nakosung** [comment]
Actually unreal.js will be available in UE4 marketplace as a free plugin. (Windows/Mac/+Linux(maybe)) In fact, I don't have enough time for making automated build and deploy env for unreal.js for all platforms. So I decided to publish the plugin with official UE4 market place(which has automated build env).

**Comment by monokrome** [comment]
Awesome! Thanks for the followup, @nakosung! :)
