### ISSUE TITLE
Breakpoints not working when debugging with Visual Studio 2015 or Visual Studio Code

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#66]
I managed to attach the NTVS debugger to localhost:5858. It seems to be working since the javascript console (in UE) says 

```
< V8 Debugger session start
```
and
```
< V8 Debugger session stop 
```

but breakpoints do not work in Visual Studio, it says

> the breakpoint will not currently be hit. no code has been loaded for this code location

and the `debugger;` keyword (in JS code) does not work.

**Comment by nakosung** [comment]
Did you try with Vscode?

**Comment by arthursw** [comment]
No because I don't know how to debug with VSCode (I didn't try since the [Debugging with Visual Studio Code](https://github.com/ncsoft/Unreal.js/wiki/Debugging-with-Visual-Studio-Code) wiki page is empty).

**Comment by arthursw** [comment]
I'll have a try.

**Comment by arthursw** [comment]
Breakpoints do not work either. I have access to global variables in the console though, and I can call functions. But UnrealJS won't stop on a breakpoint or on the debugger keyword.

**Comment by arthursw** [comment]
I updated the [Debugging with Visual Studio Code](https://github.com/ncsoft/Unreal.js/wiki/Debugging-with-Visual-Studio-Code) wiki page. 

I am not sure everything is correct, especially I should probably set the "localRoot" or "remoteRoot" parameters.

**Comment by arthursw** [comment]
I just realized that breakpoints work in `extension-spiralGenerator.js`, but not in other scripts like `helloWorld.js`. 

Could it be that I set `Context.SetAsDebugContext()` in the wrong Javascript console? 

I tried to include `Context.SetAsDebugContext()` in my js script (for example in `helloWorld.js`) but it still does not trigger breakpoints.

**Comment by nakosung** [comment]
Thanks for wiki page you updated! Regarding 'SetAsDebugContext' you are right. Please make sure there is only one 'debuggee context' set (no editor context).

**Comment by arthursw** [comment]
Ok! It works. In order to set the debug context in the correct javascript console:

 1. press Play 
 
 2. Shift + F1 to have access to the mouse, focus on the javascript console to type `Context.SetAsDebugContext()`

 3. Now attach Visual Studio Code to work with breakpoints!
