### ISSUE TITLE
Spiral generator not working

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#67]
Spiral generator was working fine (in UE 4.10, a few weeks ago), but it seems to be broken in the latest release.

It gives me this error:

```
Error: ReferenceError: JavascriptEditorViewport is not defined ReferenceError: JavascriptEditorViewport is not defined
    at main (c:\Users\Arthur Masson\Documents\Unreal Projects\Unreal.js\Examples\Content\Scripts\extension-spiralGenerator.js:167:13)
    at create_inner (c:\Program Files (x86)\Epic Games\4.11\Engine\Plugins\UnrealJS\Content\Scripts\editor-maker.js:56:25)
    at c:\Program Files (x86)\Epic Games\4.11\Engine\Plugins\UnrealJS\Content\Scripts\editor-maker.js:82:13
```

I checked the difference between the old file and the new one, the problem seems to come from the replacement of jade by UMG.

**Comment by arthursw** [comment]
I updated Unreal.js (git pull) and noticed that Spiral generator was updated recently. But now it is not recognized by the JavascriptPlayground project (I don't see it in Window > Developer tools).

**Comment by arthursw** [comment]
Sorry, my Unreal.js local repo seems to be broken, I'll retry with a fresh clone.

**Comment by arthursw** [comment]
Hum... no matter what I do, I can't get it working. When I create a fresh new project, enable the UnrealJS plugin, copy all js examples (everything from `Unreal.js/Examples/Content/Scripts/`) in `MyNewProject/Content/Scripts/`, most examples work fine, but the spiral generator is not detected (not in the `Window > Developer` tools menu).

**Comment by nakosung** [comment]
New build updated (4.11.2) :) Please check it out.
