### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by aethereality** [ncsoft/Unreal.js#69]
Following the [given tutorial](https://www.youtube.com/watch?v=XxPSLjBg7DU) down to the letter, but there is no `package.json` in my `Content/Scripts` folder which causes `npm` to fail as it cannot read dependencies. Is this tutorial out of date, or am I doing something wrong?

**Comment by nakosung** [comment]
You're right. Docs seem out of dated.

**Comment by aethereality** [comment]
@nakosung -- I'm happy to submit a PR to update them if you give me an idea of what I should be doing. At this point I'm stuck on this step. Thank you.

**Comment by nakosung** [comment]
Actually there is no more need for `npm i`. For more detailed instructions, please check video tutorials. (which are also slightly out-dated)

**Comment by aethereality** [comment]
Hello, when I try to follow the video tutorial I get the following error:
![unrealjs](https://cloud.githubusercontent.com/assets/7537913/14973933/ac7f1460-10bc-11e6-9369-49f2c91cefaf.png)

I have put the prebuilt v8 in in Unreal.js Plugins folder.

Thank you for your time.

**Comment by nakosung** [comment]
Did you try with latest build of Unreal.js and UE 4.11.2?

**Comment by aethereality** [comment]
I downloaded the latest Prebuilt Binaries(UnrealJS.Prebuilt.4.11.2-20160428.zip) and UE 4.11.2.

**Comment by nakosung** [comment]
Please follow new instructions.
