### ISSUE TITLE
type error in Proxy class on Mac

### ISSUE THREAD

**Issue by funitar** [ncsoft/Unreal.js#72]
I got this error on Mac

1) example map : HelloUMG
2) console message (in short)
    Error: TypeError: this.add_child is not a function
    Error:     at Proxy.children.forEach.child ( .../Plugins/.../Scripts/instantiator.js:232:26 )
                  at main (.../Examples/.../Scripts/helloUMG.js:261:16)

On Windows, the example works well.

**Comment by nakosung** [comment]
I think your v8 version is 5.0. V8 has changed its gc proc, it seems to behave differently. Please try with older version of v8. (4.9.385.35)

**Comment by nakosung** [comment]
82d1cbe fixed the issue.

**Comment by funitar** [comment]
yes. my v8 is 5.0.x.

For proper v8 installation, i use the commmand below,

brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/068517c055c1c1c3bf97abe0461ea5b18cc31f2c/Formula/v8.rb

**Comment by nakosung** [comment]
Did you try ncsoft/Unreal.js-core@a1b6f72?
