### ISSUE TITLE
Strange behavior when overloading Actor?

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#74]
I extended an actor this way:
```

class ProceduralMeshActor extends Actor {
    // pre-ctor; you can switch subobject to another class defined in super class.
    prector() {
    }
    
    ctor() {
    }

    properties() {
    }

    GetActorBounds() {
        console.log("GetActorBounds")
        super.GetActorBounds()
        return "A string"
    }
}

// later in my code

console.log(actor instanceof global.ProceduralMeshActor)
const Box = actor.GetActorBounds() // calls ProceduralMeshActor.GetActorBounds() (it logs "GetActorBounds") but returns some incorrect bounds instead of the string!!!
console.log(JSON.stringify(Box)) // logs the bounds: {"Origin":{"X":0,"Y":0,"Z":0},"BoxExtent":{"X":0,"Y":0,"Z":0}}

```

How is this possible?

I suppose I can't return a different type in an overloaded function. I can easily solve this problem but I am curious, I wonder why this happens.

**Comment by arthursw** [comment]
This is probably due to the Actor type declaration in the typings files (_part_0_ue.d.ts) in Unreal.js.

**Comment by nakosung** [comment]
Your JS class is just a skeleton for `uclass.js` to generate a corresponding proper Unreal class. So if you override a function which was already declared in another UClass, its signature is automatically determined from its super function. So it seems normal. I think that validation should be added for this case.
