### ISSUE TITLE
Mac Plugin Incompatible

### ISSUE THREAD

**Issue by lance0821** [ncsoft/Unreal.js#77]
I have created a new project using engine 4.11.2, then cloned the UnrealJS repo in my plugins folder, but I get plugin incompatible, module v8 missing. what I have tried: I have installed v8 4.8, 4.9, 5.0 all via brew and I have tried teh a1b6f72 commit, but still get same error.

**Comment by nakosung** [comment]
Have you installed v8 via brew?

**Comment by lance0821** [comment]
Yes each version was installed with brew

**Comment by godshow** [comment]
I have the same problem .

**Comment by nakosung** [comment]
Please check out.

https://github.com/ncsoft/Unreal.js/wiki/Mac

**Comment by EvelynY** [comment]
I have the same problem.

**Comment by nakosung** [comment]
For all Mac Users,

There is working build for Mac on another branch,
https://github.com/ncsoft/Unreal.js-core/tree/5.1.300
https://github.com/ncsoft/Unreal.js-core/releases/tag/v8-5.1.300-mac

Thanks!
