### ISSUE TITLE
how to build in MAC

### ISSUE THREAD

**Issue by godshow** [ncsoft/Unreal.js#78]
* Mac

    brew install v8
    cd your project/Plugins; git clone https://github.com/ncsoft/Unreal.js-core UnrealJS

i have follow this method ,then how to make this plugin

**Comment by nakosung** [comment]
If you setup properly, opening <your project>.uproject automatically starts to build including plugins.

**Comment by godshow** [comment]
Place the Plugins in engine or my project?

**Comment by nakosung** [comment]
Placing under your project would be fine.

**Comment by nakosung** [comment]
Please check out.
https://github.com/ncsoft/Unreal.js/wiki/Mac

**Comment by nakosung** [comment]
Your project.
2016. 5. 16. 오후 2:34에 "godshow" <notifications@github.com>님이 작성:
