### ISSUE TITLE
Sample project not loading

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#8]
It seems like everything is installed correctly. I see a Javascript console, and can define variables inside and use them.

However the sample project that loads is empty. There are no Scripts within the content browser (not sure if that's expected?)

GWorld is inaccessible as well, see screenshot

![not sure if installed](https://cloud.githubusercontent.com/assets/1041360/11356752/ae4b60e4-9215-11e5-85ac-7500e89c257c.png)

Upon trying to rebuild the sample project from its visual studio solution:
![cantfindmodule](https://cloud.githubusercontent.com/assets/1041360/11356829/39a009d8-9216-11e5-99c4-27b59dd058f1.png)

So a few questions

1. How do I ensure, from the JavascriptPlayground, that the sample and plugin is loaded correctly?
2. How do I run the actual Javascript code from within the JavascriptPlayground UE4 project?

**Comment by mflux** [comment]
I've created a blueprint for calling the JS code like so:

![jsbp](https://cloud.githubusercontent.com/assets/1041360/11357873/311648c6-9221-11e5-8e28-cb8fbd9284e1.png)

However the console will throw out warnings like:

    LogWindows: Warning: CreateProc failed (193) C:\Users\Flux\Documents\Unreal Projects\unrealjs\Content\Scripts\hellospringy.js

**Comment by nakosung** [comment]
Sample project is a blueprint only project, and editor context has no GWorld instance (please see Wiki).

Javascript files are not visible in content browser because javascript code is not an asset resource.

Anyway maps should be visible in content browser.

**Comment by mflux** [comment]
Nice! I didn't see you had a wiki with info. I got it working following the documentation:

![working](https://cloud.githubusercontent.com/assets/1041360/11358466/18ef7dc0-9227-11e5-90e1-4fddabb15d79.png)

For the record, the example file is incomplete. You have to add a new Blueprint Class, add a new Javascript Component to it, and then assign the source file in the source location. This wasn't obvious to me, probably because I'm a new UE user :p 

If anyone's ever confused in the future...

![blueprinthowto](https://cloud.githubusercontent.com/assets/1041360/11358488/72417568-9227-11e5-9e50-1525d85aef63.png)

I'll contribute some documentation once I get further into this.

**Comment by nakosung** [comment]
Yes. There is a tough road to ride on Unreal.js. https://github.com/ncsoft/Unreal.js/wiki/Bootstrap
