### ISSUE TITLE
HelloJS example not working

### ISSUE THREAD

**Issue by mflux** [ncsoft/Unreal.js#84]
This is due to Object.observe no longer being available. You're probably aware of this issue ;)

Can npm install this https://github.com/anywhichway/proxy-observe perhaps as a polyfill.

**Comment by mflux** [comment]
Full error:

Error: c:\Users\Flux\Documents\Unreal Projects\Unreal.js-master\Examples\Content\Scripts\helloJS.js:323: TypeError: Object.observe is not a function
Error: TypeError: Object.observe is not a function

**Comment by nakosung** [comment]
Oh. I have forgotten about this example. Thank you for letting me know. :+1:

**Comment by nakosung** [comment]
Resolved.

**Comment by nakosung** [comment]
Resolved.
