### ISSUE TITLE
add a cache for required modules to avoid cyclic dependencies error

### ISSUE THREAD

**Issue by gastrodia** [ncsoft/Unreal.js#85]
since unreal.js has support common.js
maybe we should have save behavior with nodejs to avoid Maximum call stack size exceeded error

https://nodejs.org/api/modules.html#modules_cycles

**Comment by nakosung** [comment]
:+1: Okay, I'll look into this problem. :)

**Comment by nakosung** [comment]
@gastrodia can you let me know the module which has cyclic ref?

**Comment by gastrodia** [comment]
It's some modules in my project develop in nodejs for sptatial circulate ,and I want reuse it in unreal.js

maybe i can give a simple example:

a.js:
var b = require('./b')
exports.name = 'a'

b.js:
var c = require('./c')
exports.name = 'b'

c.js:
var a = require('./a')
exports.name = 'c'

t.js
console.log(require('./a'))
console.log(require('./b'))
console.log(require('./c'))

then run  `node t.js ` 
result:
```
{ name: 'a' }
{ name: 'b' }
{ name: 'c' }
```

but in unreal.js it will cause Maximum call stack size exceeded error

**Comment by nakosung** [comment]
Okay, it seems to fix current behavior of 'require' implemented within unreal.js. :)

**Comment by gastrodia** [comment]
I think support supports circular dependencies it better ,so we can reuse node moudles in unreal.js (don't need rewrite it again..)
in practice , in nodejs we often do link this:

a.js:

exports.function1= function(){
   var b = require('./b')
   b.function1();
}
exports.function2=function(){
   //maybe get some info of module a
}

b.js:
exports.function1=function(){
var c = require('./c')
c.function1()
}


c.js:
exports.function1=function(){
   var a = require('./a')
   a.function2();
}

t.js
var a = require('./a');
a.function1()

**Comment by nakosung** [comment]
Actually, example you gave works fine within unreal.js. That is not a circular dependency because require is postponed after function call. :)

**Comment by gastrodia** [comment]
oh,I got it maybe it because I use typescript and I want reuse module both in backend and forntend so I import module  like this 
```
 import {A} from './A'  
```
but typescript import declaration can't used in a function maybe I need do more work to find some new solution to this... - -

**Comment by arthursw** [comment]
Did you find a solution ? I have the same problem.
