### ISSUE TITLE
Not working on latest and docs out of date.

### ISSUE THREAD

**Issue by joelutting** [ncsoft/Unreal.js#87]
Trying to get Unreal.js working on latest UE 4.12.3 and not succeeding.
first the video tutorials seem to refer to files which are no longer in github.
second I get so far and the system says it needs to recompile several .dlls as they are built with an older version, and then that recompile fails.

Is there an uptodate info on getting started?

**Comment by nakosung** [comment]
@joelutting I had tested with up-to-dated 4.12.3 and it worked well as usual. Have you tried with ready-to-build zip file? https://github.com/ncsoft/Unreal.js-core/releases

**Comment by joelutting** [comment]
I was watching a video tutorial that referred to release files that did not exist anymore on github - I tried a few thing, finally following the other video and stuff from the main page - and it all is working now.

**Comment by nakosung** [comment]
@joelutting Sorry for inconvenience. Those vids are made by friendly users(@youdaman,@keyle) and not maintained officially.
