### ISSUE TITLE
can't receive key event in example hello2048

### ISSUE THREAD

**Issue by gastrodia** [ncsoft/Unreal.js#88]
![1](https://cloud.githubusercontent.com/assets/4869158/16458133/996c200e-3e50-11e6-843a-49876abaf793.png)

![2](https://cloud.githubusercontent.com/assets/4869158/16458158/b678a46a-3e50-11e6-94e3-a72ed095a225.png)

**Comment by getnamo** [comment]
can confirm this problem

**Comment by nakosung** [comment]
I remember key input is active after clicking UI widget.

**Comment by nakosung** [comment]
I confirmed that input is enabled only after clicking some widget.
