### ISSUE TITLE
Extend JavascriptEditorViewport

### ISSUE THREAD

**Issue by arthursw** [ncsoft/Unreal.js#89]
I'm building a texture UV editor with a JavascriptEditorViewport.

I will need to customize the viewport, especially to change the camera controls.

The best is probably to create a c++ class like UJavascriptEditorViewport in my project, but I'm not sure how to use it in javascript. What should I do ?

**Comment by nakosung** [comment]
If you want to override [UpdateMouseMoveDelta](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Editor/UnrealEd/Public/EditorViewportClient.h#L601), you need to override the method to `FJavascriptEditorViewportClient`(like [this](https://github.com/ncsoft/Unreal.js-core/blob/master/Source/JavascriptEditor/JavascriptEditorViewport.cpp#L51)) and expose it to `UJavascriptEditorViewport`.(like [this](https://github.com/ncsoft/Unreal.js-core/blob/master/Source/JavascriptEditor/JavascriptEditorViewport.h#L43)).

That's all. :)

**Comment by arthursw** [comment]
Yes, I tried to reposition the camera in `OnInputWidgetDelta` but it does not really work:

```

            UMG(JavascriptEditorViewport,
            {
                OnDraw:(_PDI,elem) => { [...]  },
                OnTrackingStarted: (InInputState, bIsDraggingWidget, bNudge)=> {
                    console.log("OnTrackingStarted")
                },
                OnTrackingStopped: ()=> {
                    console.log("OnTrackingStopped")
                },
                OnInputWidgetDelta: (Drag, Rot, Scale) => {
                    this.CameraPosition = this.CameraPosition.AddV(Drag)
                    this.Viewport.SetViewLocation(this.CameraPosition)

                    // I need an orthographic top view:
                    let Rotation = new Rotator()
                    Rotation.Pitch = 90
                    this.Viewport.SetViewRotation(Rotation) 
                },
                [...]
            },[...]
        )
```

I would need to disable the default camera moves.

**Comment by nakosung** [comment]
I think you need access to `SetCameraLock, IsCameraLocked` of `FEditorViewportClient`. Is it right?

**Comment by arthursw** [comment]
Yes, so I will make a custom c++ class similar to JavascriptEditorViewport. 
How can I make it available in Javascript ?

**Comment by nakosung** [comment]
1. Copy JavascriptEditorViewport.* to YourJavascriptEditorViewport.* and rename classes.
2. Add appropriate accessor methods to UJavascriptEditorViewport and make it sure to call corresponding method of FJavascriptEditorViewport instance.

:)

**Comment by arthursw** [comment]
Ok, I suppose that all UClass are accessible in JS by default.

I tried to copy JavascriptEditorViewport.* files to my project, but I had problem to include related Unreal.js files (`JavascriptEditorLibrary.h` and `JavascriptEditor.h`). So I decided to just modify Unreal.js directly.

The problem is that when I call `FEditorViewportClient::EnableCameraLock(true)` the viewport is empty (no matter where I set the camera with `FEditorViewportClient::SetViewLocation()`) and when I drag/move/zoom with the mouse in the viewport the camera moves to invalid locations like:
`X=-479474336.000 Y=-308180032.000 Z=-1167343872.000
`

So I need another way to take control of the camera.

**Comment by arthursw** [comment]
Ok, setting `SetViewportType(ELevelViewportType.LVT_OrthoXY)` gives me the camera I want. Now I just need to enable the selection rectangle and widget to select and move objects around.

**Comment by nakosung** [comment]
Widget functions are accessible with current version of UJavascriptEditorViewport. Unfortunately I don't have any experience with selection rectangle, which I haven't seen before in UE4Ed.

**Comment by arthursw** [comment]
1. To move the widget around I used `FEditorViewportClient::GetWidgetLocation`. 

 2. I manually implemented the selection rectangle by extending the `FEditorViewportClient::Draw(FViewport* Viewport, FCanvas* Canvas)`.
