### ISSUE TITLE
extension-exampleWindow.js#L290 causes hitching

### ISSUE THREAD

**Issue by getnamo** [ncsoft/Unreal.js#91]
temporary fix https://github.com/getnamo/Unreal.js/commit/4415cee73b6f0e4e2e1fa3994d94cd231651ddc9

Will only refresh the repositories once, after that it will not impact others.

A proper fix would be to optimize https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/extension-exampleWindow.js#L290

and/or remove its tick function if the window gets closed. How do you detect when an editor window closes?

**Comment by nakosung** [comment]
Removed repeated polling. :)
