### ISSUE TITLE
Scripts dont run after packaging

### ISSUE THREAD

**Issue by MasonSidebottom** [ncsoft/Unreal.js#94]
I am using unreal.js for AI's in my game, when packaging the game, I lose all of the AI functionality. Is there a specific process that I must go through to allow the scripts to be kept in the packaging process?

Thanks, 
Mason

**Comment by nakosung** [comment]
https://github.com/ncsoft/Unreal.js/wiki/Cooking

This might be helpful.

**Comment by MasonSidebottom** [comment]
Nako,

I've been toying around with the packaging this morning, the closest I have come is to get a plugins directory in the directory as the packaged .exe  directory; however, this only includes the .uplugin file with no additional directories. 
![capture](https://cloud.githubusercontent.com/assets/16109260/16901474/bfdd5d14-4bf9-11e6-960d-ae6ddb7d4803.JPG)

Do I need to include a specific file somewhere in my C++ code? Or is there a setting that I need to adjust in the packaging settings? 

Cheers,
Mason

**Comment by nakosung** [comment]
There is an option which describes files to be packed. (File - Package Project - Packaging Settings - Advanced options - Additional Non-Asset Directories to Package) 

1. Copy all your UnrealJS/Content/Scripts into {YourProject}/Content/Scripts
2. Add {YourProject}/Content/Scripts in package settings/additional directories to package (I'm not sure which option is right)

**Comment by MasonSidebottom** [comment]
Seems to work! Thanks!

Now I am getting a JS error

> [2016.07.18-19.08.58:718][126]Javascript:Error: d:\Development\pd_4_11\Content\Scripts\uclass.js:88: TypeError: Cannot read property 'constructor' of null
[2016.07.18-19.08.58:719][126]Javascript:Error: TypeError: Cannot read property 'constructor' of null
[2016.07.18-19.08.58:719][126]Javascript:Error:     at register (d:\Development\pd_4_11\Content\Scripts\uclass.js:88:72)
[2016.07.18-19.08.58:719][126]Javascript:Error:     at d:/Development/pd_4_11/Content/Scripts/mainAIHandler.js:37:35
[2016.07.18-19.08.58:719][126]Javascript:Error:     at d:/Development/pd_4_11/Content/Scripts/mainAIHandler.js:67:3
from this line

`let mainAI_C = require('uclass')()(global,mainAI)`

mainAI was declared like this:

```
class mainAI extends Root.ResolveClass('./Game/MCBP') {
    // constructor
    ctor() {
        // Subobject initialization, property initialization
        this.bAlwaysRelevant = true
        this.Command = require('./commandFunctions/command.js')
    }
    tester(){
        var commandCenter = new this.Command(this.Planets, this.Fleets, this.botFile, this.playerID)
        this.Commands = commandCenter.artificialIntelligence()
    }
}

```

Am I extending the class incorrectly?

**Comment by nakosung** [comment]
ResolveClass requires *asset-name*(not asset-path) which you used to register your BP class with. Those assets should be registered in `ClassAssets` in JavascriptComponent.

**Comment by MasonSidebottom** [comment]
Awesome, that worked perfectly. Thank you for you help!

Cheers, 
Mason

**Comment by hamkoo** [comment]
@MasonSidebottom @nakosung 
It's ok to play or launch in UE4 Editor or packaged,but cannot run js after pacakged with "Use Pak File" checked. 
![image](https://user-images.githubusercontent.com/321692/43307140-021f5832-91b0-11e8-8a86-afc89d1011d5.png)
