### ISSUE TITLE
Using a transpiler with Unreal.js

### ISSUE THREAD

**Issue by jcoder58** [ncsoft/Unreal.js#96]
I'm looking at using [Fable](http://fsprojects.github.io/Fable/docs/interacting.html) to implement F# for UE4.  Fable is an node console application that transpiles F# into Javascript.

What is the best approach for using a transpiler with Unreal.js?  Ideally, I would like to have live loading with the F# code.  Another issue is exporting F# interface for the UE4 API.

**Comment by nakosung** [comment]
Transplied js code runs smoothly within unreal.js? If so, you can setup watching and auto recompilation using gulp within your favorite dev-env(like vscode, sublime, ...).

**Comment by mflux** [comment]
I transpile to ES6 perfectly using Babelify / Grunt.

**Comment by nakosung** [comment]
This issue seems to be done.
