### ISSUE TITLE
How to export class

### ISSUE THREAD

**Issue by ghost** [ncsoft/Unreal.js#98]
After defining a class in a file, how to export this class? So that other files can get this class defination and use it?
I tried module.exports, exports, export. But none of then worked. And I didn't find such example in your samples.

**Comment by nakosung** [comment]
@saohddz Do you mean 'js' class or 'uclass'? 'uclass' is registered in global scope so you can access it anywhere.

**Comment by nakosung** [comment]
this issue seems dead.
