### ISSUE TITLE
Testing Examples - TypeError: require(...) is not a function in console MAC

### ISSUE THREAD

**Issue by hexenskull** [ncsoft/Unreal.js#99]
It took me as for newbie one day to finally install it on my Mac. So now I can use console as calculator in my project. But I can't run nothing from examples JavascriptPlayground.uproject

It is so dramatic.

Here is log from console:

```
Javascript:Error: /Users/hexen/Desktop/UREAL_JS/Unreal.js-master/Examples/Content/Scripts/bootstrap.js:12: TypeError: require(...) is not a function
Javascript:Error: TypeError: require(...) is not a function
Javascript:Error:     at module.exports (/Users/hexen/Desktop/UREAL_JS/Unreal.js-master/Examples/Content/Scripts/bootstrap.js:12:30)
Javascript:Error:     at /Users/hexen/Desktop/UREAL_JS/Unreal.js-master/Examples/Content/Scripts/helloCharacter.js:124:25
Javascript:Error:     at /Users/hexen/Desktop/UREAL_JS/Unreal.js-master/Examples/Content/Scripts/helloCharacter.js:127:3
```

Files to build plugin downloaded from here: https://github.com/ncsoft/Unreal.js-core/releases/tag/V8-5.1.300

Is it a problem of V8? Cause **homebrew** installed me this version: **v8-5.1.281.47.el_capitan.bottle.tar.gz**
Do I have to instal newer?

What am I doing wrong?

UPDATE 09.08.2016

I've installed Windows on Mac using Bootcamp and I'm still facing the same issue. Output logs are the same! Obviously it is not a problem of plugin itself. It's me doing something wrong. There are no clues on the web how to solve this problem neither in the issues with this git repo.

Please help me someone.

______________________

UPDATE 09.08.2016

Finally I got this working on Windows! Thank god!
The problem was that I just downloaded prebuilded version of plugin from **releases** and it was a huge mistake. 

SO I just should had downloaded it from this page:
https://github.com/ncsoft/Unreal.js-core/tree/bf25fc27e7f955946c5696aff71553ce3df95974

**Comment by mflux** [comment]
@hexenskull what was the difference between the releases build and the one you linked? Why did that one work?
